force-app/main/default/objects/Lead_Report_Id__c/Lead_Report_Id__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Lead Report Id</label>
</CustomObject>

force-app/main/default/objects/Lead_Report_Id__c/fields/Allowed_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Accounts__c</fullName>
    <label>Allowed Accounts</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead_Report_Id__c/fields/Allowed_Emails__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Emails__c</fullName>
    <label>Allowed Emails</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Report_Id__c/fields/Send_To_All__c.field-meta.xml
<CustomField>
    <fullName>Send_To_All__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send To All</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LeadReportUpdatedSchedulerTest.cls
@isTest
public class LeadReportUpdatedSchedulerTest {

    @isTest static void testAt7AM() {
        Account acc = new Account(
            Name = 'Test Dealer',
            Center_Code__c = 'D001',
            Email__c = 'dealer@test.com'
        );
        insert acc;
        
        Lead_Report_Id__c setting = new Lead_Report_Id__c(
            Name = 'Lead Report Id',
            Send_To_All__c = true,
            Allowed_Accounts__c = acc.Id,
            Allowed_Emails__c = 'extra1@test.com,extra2@test.com'
        );
        insert setting;

        Test.startTest();
        System.schedule('Job7AM', '0 0 7 * * ?', new LeadReportUpdatedScheduler());
        Test.stopTest();
    }

    @isTest static void testAt7PM() {
        Account acc = new Account(
            Name = 'Test Dealer',
            Center_Code__c = 'D001',
            Email__c = 'dealer@test.com'
        );
        insert acc;
        
        Lead_Report_Id__c setting = new Lead_Report_Id__c(
            Name = 'Lead Report Id',
            Send_To_All__c = true,
            Allowed_Accounts__c = acc.Id,
            Allowed_Emails__c = 'extra1@test.com,extra2@test.com'
        );
        insert setting;

        Test.startTest();
        System.schedule('Job7PM', '0 0 19 * * ?', new LeadReportUpdatedScheduler());
        Test.stopTest();
    }

    @isTest static void testAtOtherTime() {
        Account acc = new Account(
            Name = 'Test Dealer',
            Center_Code__c = 'D001',
            Email__c = 'dealer@test.com'
        );
        insert acc;
        
        Lead_Report_Id__c setting = new Lead_Report_Id__c(
            Name = 'Lead Report Id',
            Send_To_All__c = true,
            Allowed_Accounts__c = acc.Id,
            Allowed_Emails__c = 'extra1@test.com,extra2@test.com'
        );
        insert setting;

        Test.startTest();
        System.schedule('Job10AM', '0 0 10 * * ?', new LeadReportUpdatedScheduler());
        Test.stopTest();
    }
}