force-app/main/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <label>Test Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Drive__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Ride_Type__c.field-meta.xml
<CustomField>
    <fullName>Ride_Type__c</fullName>
    <label>Ride Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HTR</fullName>
            </value>
            <value>
                <fullName>STR</fullName>
            </value>
            <value>
                <fullName>Home Ride</fullName>
            </value>
            <value>
                <fullName>Store Ride</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Test_Ride_Date__c.field-meta.xml
<CustomField>
    <fullName>Test_Ride_Date__c</fullName>
    <label>Test Ride Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TestRideCreateWhatsappmsgcallout_test.cls
@istest 
public class TestRideCreateWhatsappmsgcallout_test {
 @isTest
    public static void testTriggerLogicAndCallout() {
        // Step 1: Set up test data
        Lead leadRecord = new Lead(
            FirstName = 'Test',
            LastName = 'Lead',
            Phone = '1234567890',
            LeadSource = 'Google',
            Dealer_Code__c = '291001',
            Company='NA'
        );
        insert leadRecord;

        Test_Drive__c testDriveRecord = new Test_Drive__c(
            Name = 'Test Ride',
            Lead__c = leadRecord.Id,
            Test_Ride_Date__c = System.now(),
            Ride_Type__c = 'STR'
        );
        insert testDriveRecord;

        // Step 2: Mock the HTTP response
        Test.setMock(HttpCalloutMock.class, new TestRideCreateWhatsappmsgcallout_mock());

        
       
    }
}