force-app/main/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <label>Test Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Drive__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Ride_Type__c.field-meta.xml
<CustomField>
    <fullName>Ride_Type__c</fullName>
    <label>Ride Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HTR</fullName>
            </value>
            <value>
                <fullName>STR</fullName>
            </value>
            <value>
                <fullName>Home Ride</fullName>
            </value>
            <value>
                <fullName>Store Ride</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Test_Drive_Status__c.field-meta.xml
<CustomField>
    <fullName>Test_Drive_Status__c</fullName>
    <label>Test Drive Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Test_Ride_Date__c.field-meta.xml
<CustomField>
    <fullName>Test_Ride_Date__c</fullName>
    <label>Test Ride Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/WhatsAppMsgForTestrideComplete_test.cls
@istest
public class WhatsAppMsgForTestrideComplete_test {
     @isTest
    public static void testTriggerAndCallout() {
        Test.setMock(HttpCalloutMock.class, new Mock_callout_response_for_testridenoshow());

        Lead leadids = new Lead(FirstName = 'John', LastName = 'Doe', Phone = '919632584820',Company='NA',  Dealer_Code__c='291002',
                LeadSource='91Wheels');
        insert leadids;

               Test_Drive__c testDrive = new Test_Drive__c(
            Name = 'Test Ride',
            Lead__c = leadids.Id,
            Test_Ride_Date__c = System.now(),
            Ride_Type__c = 'Store Ride'
        );
        insert testDrive;

        testDrive.Test_Drive_Status__c = 'Completed';
        update testDrive;


        
    }


}