force-app/main/default/objects/RR_Additional_Job_Recommended__c/RR_Additional_Job_Recommended__c.object-meta.xml
<CustomObject>
    <label>Additional Job Recommended</label>
    <nameField>
        <displayFormat>AJ-{0000}</displayFormat>
        <label>Additional Job No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Jobs Recommended</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RR_Additional_Job_Recommended__c/fields/RR_Product__c.field-meta.xml
<CustomField>
    <fullName>RR_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an active product.</errorMessage>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Additional Jobs Recommended</relationshipLabel>
    <relationshipName>Additional_Jobs_Recommended</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RR_Additional_Job_Recommended__c/fields/RR_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>RR_Unit_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/RR_Additional_Job_Recommended_Handler.cls
public class RR_Additional_Job_Recommended_Handler {
    public static void handleUnitPriceUpdate(List<RR_Additional_Job_Recommended__c> additionalJobs) {
        Set<Id> productIds = new Set<Id>();
        for (RR_Additional_Job_Recommended__c additionalJob : additionalJobs) {
            if (additionalJob.RR_Product__c != null) {
                productIds.add(additionalJob.RR_Product__c);
            }
        }

        Map<Id, PricebookEntry> productPriceBookEntries = new Map<Id, PricebookEntry>();
        for (PricebookEntry pbe : [SELECT Product2Id, UnitPrice FROM PricebookEntry WHERE Product2Id IN :productIds]) {
            productPriceBookEntries.put(pbe.Product2Id, pbe);
        }

        for (RR_Additional_Job_Recommended__c additionalJob : additionalJobs) {
            if (additionalJob.RR_Product__c != null) {
                PricebookEntry pbe = productPriceBookEntries.get(additionalJob.RR_Product__c);
                if (pbe != null) {
                    additionalJob.RR_Unit_Price__c = pbe.UnitPrice;
                }
            }
        }
    }
}