force-app/main/default/objects/Salesforce_Support__c/Salesforce_Support__c.object-meta.xml
<CustomObject>
    <label>Salesforce Support</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Support</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_Support__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PDI</fullName>
            </value>
            <value>
                <fullName>Lead Management System</fullName>
            </value>
            <value>
                <fullName>Order Management System</fullName>
            </value>
            <value>
                <fullName>Job Card Process</fullName>
            </value>
            <value>
                <fullName>Case Management</fullName>
            </value>
            <value>
                <fullName>Credential Related Issues</fullName>
            </value>
            <value>
                <fullName>Warranty Management Issue</fullName>
            </value>
            <value>
                <fullName>Vehicle Related Issue</fullName>
            </value>
            <value>
                <fullName>Inventory Management</fullName>
            </value>
            <value>
                <fullName>Service Lapse Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SalesforceTicketController_Test.cls
@isTest
private class SalesforceTicketController_Test {
    
    @TestSetup
    static void makeData(){
        
        Contact testContact = new Contact(
            LastName = 'Smith',
            FirstName = 'John',
            Designation__c = 'Technical Support',
            Phone = '8978675467'
        );
        insert testContact;

        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User testUser = new User(
            FirstName = 'Jane',
            LastName = 'Doe',
            Email = 'janedoe@example.com',
            Username = 'janedoe' + DateTime.now().getTime() + '@example.com',
            Alias = 'jdoe',
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            ProfileId = p.Id
        );
        insert testUser;

        Salesforce_Support__c ticket = new Salesforce_Support__c(
            Status__c = 'Open',
            Subject__c = 'Test Subject'
        );
        insert ticket;
    }

    @isTest
    private static void test_getSalesforceSupportRecords(){

        List<Salesforce_Support__c> testRecords = new List<Salesforce_Support__c>();

        testRecords.add(new Salesforce_Support__c(
            Status__c = 'Open',
            Subject__c = 'Subject 1',
            Description__c = 'Test Description 2'
        ));

        testRecords.add(new Salesforce_Support__c(
            Status__c = 'Closed',
            Subject__c = 'Subject 2',
            Description__c = 'Test Description 2'
        ));

        insert testRecords;

        SalesforceTicketController.getSalesforceSupportRecords(); 
    }

    @isTest
    private static void test_GetContactAndUserOptions() {

        List<SalesforceTicketController.ContactUserWrapper> results = SalesforceTicketController.getContactAndUserOptions();        
    }

    @isTest
    private static void test_CreateTicketAssignment() {

        Salesforce_Support__c tckt = [SELECT Id FROM Salesforce_Support__c WHERE Status__c = 'Open' AND Subject__c = 'Test Subject' LIMIT 1];
        User usr = [SELECT Id FROM User WHERE FirstName = 'Jane' LIMIT 1];
        Contact con = [SELECT Id FROM Contact WHERE LastName = 'Smith' LIMIT 1];

        System.debug(tckt.Id + ' ----- ' + usr.Id + ' ----- ' + con.Id);

        String msg = SalesforceTicketController.createTicketAssignment(tckt.Id, usr.Id, con.Id, 'Test Remarks', 'High');
    }
}