force-app/main/default/objects/Salesforce_Support__c/Salesforce_Support__c.object-meta.xml
<CustomObject>
    <label>Salesforce Support</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Support</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_Support__c/fields/Additional_Details__c.field-meta.xml
<CustomField>
    <fullName>Additional_Details__c</fullName>
    <label>Additional Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Closing_Date__c.field-meta.xml
<CustomField>
    <fullName>Closing_Date__c</fullName>
    <label>Closing Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Salesforce Support</relationshipLabel>
    <relationshipName>Salesforce_Support</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Internal_Team_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Internal_Team_Remarks__c</fullName>
    <label>Internal Team Remarks</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/location__c.field-meta.xml
<CustomField>
    <fullName>location__c</fullName>
    <formula>CreatedBy.Contact.Location__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PDI</fullName>
            </value>
            <value>
                <fullName>Lead Management System</fullName>
            </value>
            <value>
                <fullName>Order Management System</fullName>
            </value>
            <value>
                <fullName>Job Card Process</fullName>
            </value>
            <value>
                <fullName>Case Management</fullName>
            </value>
            <value>
                <fullName>Credential Related Issues</fullName>
            </value>
            <value>
                <fullName>Warranty Management Issue</fullName>
            </value>
            <value>
                <fullName>Vehicle Related Issue</fullName>
            </value>
            <value>
                <fullName>Inventory Management</fullName>
            </value>
            <value>
                <fullName>Service Lapse Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Team_Analysis__c.field-meta.xml
<CustomField>
    <fullName>Team_Analysis__c</fullName>
    <label>Team Analysis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recurring Issue</fullName>
            </value>
            <value>
                <fullName>Training Needed</fullName>
            </value>
            <value>
                <fullName>Post Deployment Issue</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Ticket_Age__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Age__c</fullName>
    <formula>IF(
  NOT(ISBLANK(Closing_Date__c)),

  IF(
    (Closing_Date__c - CreatedDate) * 86400 &lt; 60,
    TEXT(ROUND((Closing_Date__c - CreatedDate) * 86400, 0)) &amp; &quot; seconds&quot;,

    IF(
      (Closing_Date__c - CreatedDate) * 1440 &lt; 60,
      TEXT(FLOOR((Closing_Date__c - CreatedDate) * 1440)) &amp; &quot; minutes &quot; &amp;
      TEXT(ROUND(MOD((Closing_Date__c - CreatedDate) * 86400, 60), 0)) &amp; &quot; seconds&quot;,

      IF(
        (Closing_Date__c - CreatedDate) * 24 &lt; 24,
        TEXT(FLOOR((Closing_Date__c - CreatedDate) * 24)) &amp; &quot; hours &quot; &amp;
        TEXT(FLOOR(MOD((Closing_Date__c - CreatedDate) * 1440, 60))) &amp; &quot; minutes &quot; &amp;
        TEXT(ROUND(MOD((Closing_Date__c - CreatedDate) * 86400, 60), 0)) &amp; &quot; seconds&quot;,

        TEXT(FLOOR((Closing_Date__c - CreatedDate))) &amp; &quot; days &quot; &amp;
        TEXT(FLOOR(MOD((Closing_Date__c - CreatedDate) * 24, 24))) &amp; &quot; hours &quot; &amp;
        TEXT(FLOOR(MOD((Closing_Date__c - CreatedDate) * 1440, 60))) &amp; &quot; minutes &quot; &amp;
        TEXT(ROUND(MOD((Closing_Date__c - CreatedDate) * 86400, 60), 0)) &amp; &quot; seconds&quot;
      )
    )
  ),

  IF(
    (NOW() - CreatedDate) * 86400 &lt; 60,
    TEXT(ROUND((NOW() - CreatedDate) * 86400, 0)) &amp; &quot; seconds&quot;,

    IF(
      (NOW() - CreatedDate) * 1440 &lt; 60,
      TEXT(FLOOR((NOW() - CreatedDate) * 1440)) &amp; &quot; minutes &quot; &amp;
      TEXT(ROUND(MOD((NOW() - CreatedDate) * 86400, 60), 0)) &amp; &quot; seconds&quot;,

      IF(
        (NOW() - CreatedDate) * 24 &lt; 24,
        TEXT(FLOOR((NOW() - CreatedDate) * 24)) &amp; &quot; hours &quot; &amp;
        TEXT(FLOOR(MOD((NOW() - CreatedDate) * 1440, 60))) &amp; &quot; minutes &quot; &amp;
        TEXT(ROUND(MOD((NOW() - CreatedDate) * 86400, 60), 0)) &amp; &quot; seconds&quot;,

        TEXT(FLOOR((NOW() - CreatedDate))) &amp; &quot; days &quot; &amp;
        TEXT(FLOOR(MOD((NOW() - CreatedDate) * 24, 24))) &amp; &quot; hours &quot; &amp;
        TEXT(FLOOR(MOD((NOW() - CreatedDate) * 1440, 60))) &amp; &quot; minutes &quot; &amp;
        TEXT(ROUND(MOD((NOW() - CreatedDate) * 86400, 60), 0)) &amp; &quot; seconds&quot;
      )
    )
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ticket Age</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>TI -{00000}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complained Resolved via Explaination</fullName>
            </value>
            <value>
                <fullName>Call Later</fullName>
            </value>
            <value>
                <fullName>Appointment Requested</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Re Open</fullName>
            </value>
            <value>
                <fullName>POC Assigned</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Resolution Under Review</fullName>
            </value>
            <value>
                <fullName>Pending Rivision</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Solution not accepted</fullName>
            </value>
            <value>
                <fullName>NFA</fullName>
            </value>
            <value>
                <fullName>Call Back Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket_Assignment__c/Ticket_Assignment__c.object-meta.xml
<CustomObject>
    <label>Ticket Assignment</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Ticket Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket_Assignment__c/fields/Assigned_By__c.field-meta.xml
<CustomField>
    <fullName>Assigned_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Ticket_Assignment1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket_Assignment__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Ticket_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket_Assignment__c/fields/Assignment_Date__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Date__c</fullName>
    <label>Assignment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ticket_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ticket Assignment</relationshipLabel>
    <relationshipName>Ticket_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket_Assignment__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Salesforce Support</description>
    <inlineHelpText>Salesforce Support</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Salesforce_Support__c</referenceTo>
    <relationshipLabel>Ticket Assignment</relationshipLabel>
    <relationshipName>Ticket_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesforceTicketController.cls
public class SalesforceTicketController {
    
    @AuraEnabled(cacheable=true)
    public static List<Salesforce_Support__c> getSalesforceSupportRecords(){

        try{
            System.debug('---------------- Inside getSalesforceSupportRecords() ----------------');
            return [
                SELECT Id, Name, Status__c, Subject__c, Description__c, Internal_Team_Remarks__c, Team_Analysis__c, Additional_Details__c, CreatedById,
                Ticket_Age__c, Closing_Date__c, location__c, CreatedDate
                FROM Salesforce_Support__c
                WHERE Status__c != 'Closed'
                OR CreatedDate = TODAY
            ];
        }
        catch(Exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<ContactUserWrapper> getContactAndUserOptions(){
        try {
            System.debug('---------------- Inside getContactAndUserOptions() ----------------');

            List<ContactUserWrapper> lstContactUserWrapper = new List<ContactUserWrapper>();

            for(Contact c : [
                SELECT Id, FirstName, LastName, Name
                FROM Contact
                WHERE Designation__c = 'Technical Support'
            ]){
                lstContactUserWrapper.add(new ContactUserWrapper(c.Name, c.Id, 'Contact'));
            }

            for(User u : [
                SELECT Id, Name, Email 
                FROM User
                WHERE IsActive = true
                LIMIT 5
            ]){
                lstContactUserWrapper.add(new ContactUserWrapper(u.Name, u.Id, 'User'));
            }

            return lstContactUserWrapper;
        }
        catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static String createTicketAssignment(Id ticketId, Id userId, Id contactId, String remarks, String priority) {
        
        System.debug('ticketId : ' + ticketId + '   &&   userId : ' + userId + '   &&   remarks : ' + remarks + '   &&   priority : ' + priority);

        try{
            System.debug('---------------- Inside createTicketAssignment() ----------------');

            Ticket_Assignment__c ta = new Ticket_Assignment__c();
            ta.Ticket__c = ticketId;
            ta.Assigned_To__c = userId != null ? userId : null;
            ta.Contact__c = contactId != null ? contactId : null;
            ta.Assigned_By__c = UserInfo.getUserId();
            ta.Assignment_Date__c = System.now();
            ta.Remarks__c = remarks;
            ta.Priority__c = priority;

            insert ta;

            return 'Ticket Assigned Successfully !!';
        }
        catch(Exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }


    // Wrapper Class
    public class ContactUserWrapper{

        @AuraEnabled public String label;
        @AuraEnabled public String value;
        @AuraEnabled public String type;

        public ContactUserWrapper(String label, String value, String type){
            this.label = label;
            this.value = value;
            this.type  = type;
        }
    }
}