force-app/main/default/objects/Salesforce_Support__c/Salesforce_Support__c.object-meta.xml
<CustomObject>
    <label>Salesforce Support</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Support</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_Support__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Salesforce Support</relationshipLabel>
    <relationshipName>Salesforce_Support</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Additional_Details__c.field-meta.xml
<CustomField>
    <fullName>Additional_Details__c</fullName>
    <label>Additional Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Closing_Date__c.field-meta.xml
<CustomField>
    <fullName>Closing_Date__c</fullName>
    <label>Closing Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Salesforce Support</relationshipLabel>
    <relationshipName>Salesforce_Support</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Created_By_Name__c.field-meta.xml
<CustomField>
    <fullName>Created_By_Name__c</fullName>
    <formula>CreatedBy.Username</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created By Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Internal_Team_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Internal_Team_Remarks__c</fullName>
    <label>Internal Team Remarks</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PDI</fullName>
            </value>
            <value>
                <fullName>Lead Management System</fullName>
            </value>
            <value>
                <fullName>Order Management System</fullName>
            </value>
            <value>
                <fullName>Job Card Process</fullName>
            </value>
            <value>
                <fullName>Case Management</fullName>
            </value>
            <value>
                <fullName>Credential Related Issues</fullName>
            </value>
            <value>
                <fullName>Warranty Management Issue</fullName>
            </value>
            <value>
                <fullName>Vehicle Related Issue</fullName>
            </value>
            <value>
                <fullName>Inventory Management</fullName>
            </value>
            <value>
                <fullName>Service Lapse Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Supporting_Topics__c.field-meta.xml
<CustomField>
    <fullName>Supporting_Topics__c</fullName>
    <label>Supporting Topics</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Subject__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Lead Creation</fullName>
            </value>
            <value>
                <fullName>Test Ride Related</fullName>
            </value>
            <value>
                <fullName>Follow-up Related</fullName>
            </value>
            <value>
                <fullName>Lead Visibility</fullName>
            </value>
            <value>
                <fullName>Lead Transfer</fullName>
            </value>
            <value>
                <fullName>Account Visibility</fullName>
            </value>
            <value>
                <fullName>Account Details Related</fullName>
            </value>
            <value>
                <fullName>Phone Number Change</fullName>
            </value>
            <value>
                <fullName>Order Products Related</fullName>
            </value>
            <value>
                <fullName>Order Amount Related</fullName>
            </value>
            <value>
                <fullName>Order Invoice Related</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Vehicle Not Visible Under Store Account</fullName>
            </value>
            <value>
                <fullName>Vehicle Not Uploaded in Salesforce</fullName>
            </value>
            <value>
                <fullName>Vehicle Details Missing</fullName>
            </value>
            <value>
                <fullName>PDI Access Not Available</fullName>
            </value>
            <value>
                <fullName>PDI PDF Related Issue</fullName>
            </value>
            <value>
                <fullName>PDI Checklist Not Reflecting</fullName>
            </value>
            <value>
                <fullName>Job Card Not Opening</fullName>
            </value>
            <value>
                <fullName>Vehicle Not Found</fullName>
            </value>
            <value>
                <fullName>Parts/Labour Assignment Issue</fullName>
            </value>
            <value>
                <fullName>Parts/Labour Deletion Issue</fullName>
            </value>
            <value>
                <fullName>Invoice Related Issue</fullName>
            </value>
            <value>
                <fullName>Inventory Not Found</fullName>
            </value>
            <value>
                <fullName>Unable to Login</fullName>
            </value>
            <value>
                <fullName>Need New Credentials</fullName>
            </value>
            <value>
                <fullName>Need to Block Credentials</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Team_Analysis__c.field-meta.xml
<CustomField>
    <fullName>Team_Analysis__c</fullName>
    <label>Team Analysis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recurring Issue</fullName>
            </value>
            <value>
                <fullName>Training Needed</fullName>
            </value>
            <value>
                <fullName>Post Deployment Issue</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Ticket_Age__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Age__c</fullName>
    <formula>IF(
  NOT(ISBLANK(Closing_Date__c)),

  IF(
    (Closing_Date__c - CreatedDate) * 86400 &lt; 60,
    TEXT(ROUND((Closing_Date__c - CreatedDate) * 86400, 0)) &amp; &quot; seconds&quot;,

    IF(
      (Closing_Date__c - CreatedDate) * 1440 &lt; 60,
      TEXT(FLOOR((Closing_Date__c - CreatedDate) * 1440)) &amp; &quot; minutes &quot; &amp;
      TEXT(ROUND(MOD((Closing_Date__c - CreatedDate) * 86400, 60), 0)) &amp; &quot; seconds&quot;,

      IF(
        (Closing_Date__c - CreatedDate) * 24 &lt; 24,
        TEXT(FLOOR((Closing_Date__c - CreatedDate) * 24)) &amp; &quot; hours &quot; &amp;
        TEXT(FLOOR(MOD((Closing_Date__c - CreatedDate) * 1440, 60))) &amp; &quot; minutes &quot; &amp;
        TEXT(ROUND(MOD((Closing_Date__c - CreatedDate) * 86400, 60), 0)) &amp; &quot; seconds&quot;,

        TEXT(FLOOR((Closing_Date__c - CreatedDate))) &amp; &quot; days &quot; &amp;
        TEXT(FLOOR(MOD((Closing_Date__c - CreatedDate) * 24, 24))) &amp; &quot; hours &quot; &amp;
        TEXT(FLOOR(MOD((Closing_Date__c - CreatedDate) * 1440, 60))) &amp; &quot; minutes &quot; &amp;
        TEXT(ROUND(MOD((Closing_Date__c - CreatedDate) * 86400, 60), 0)) &amp; &quot; seconds&quot;
      )
    )
  ),

  IF(
    (NOW() - CreatedDate) * 86400 &lt; 60,
    TEXT(ROUND((NOW() - CreatedDate) * 86400, 0)) &amp; &quot; seconds&quot;,

    IF(
      (NOW() - CreatedDate) * 1440 &lt; 60,
      TEXT(FLOOR((NOW() - CreatedDate) * 1440)) &amp; &quot; minutes &quot; &amp;
      TEXT(ROUND(MOD((NOW() - CreatedDate) * 86400, 60), 0)) &amp; &quot; seconds&quot;,

      IF(
        (NOW() - CreatedDate) * 24 &lt; 24,
        TEXT(FLOOR((NOW() - CreatedDate) * 24)) &amp; &quot; hours &quot; &amp;
        TEXT(FLOOR(MOD((NOW() - CreatedDate) * 1440, 60))) &amp; &quot; minutes &quot; &amp;
        TEXT(ROUND(MOD((NOW() - CreatedDate) * 86400, 60), 0)) &amp; &quot; seconds&quot;,

        TEXT(FLOOR((NOW() - CreatedDate))) &amp; &quot; days &quot; &amp;
        TEXT(FLOOR(MOD((NOW() - CreatedDate) * 24, 24))) &amp; &quot; hours &quot; &amp;
        TEXT(FLOOR(MOD((NOW() - CreatedDate) * 1440, 60))) &amp; &quot; minutes &quot; &amp;
        TEXT(ROUND(MOD((NOW() - CreatedDate) * 86400, 60), 0)) &amp; &quot; seconds&quot;
      )
    )
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ticket Age</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Salesforce_Support__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General Query</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Urgent Complaint</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MobileApp_EventTicket.cls
@RestResource(urlMapping='/EventTicket')
global class MobileApp_EventTicket {
    @Httppost
    global static void getTickets() {
        try {
            RestRequest req = RestContext.request;
            String requestString = req.requestBody != null ? req.requestBody.toString() : '';
            if (String.isBlank(requestString)) {
                MobileApp_Wrapper.setResponse(400, 'Empty request body', null);
                return;
            }

            MobileApp_Wrapper.MobileApp_LeadTotalLeadsWrapper wrp = 
                (MobileApp_Wrapper.MobileApp_LeadTotalLeadsWrapper) JSON.deserialize(
                    requestString, 
                    MobileApp_Wrapper.MobileApp_LeadTotalLeadsWrapper.class
                );

            if (wrp.UserId == null || String.isBlank(wrp.UserId) || wrp.UserId == '') {
                MobileApp_Wrapper.setResponse(401, 'Please provide UserId', null);
                return;
            }

            String userId = UserInfo.getUserId();

            String addQuery = ' AND CreatedDate = THIS_MONTH';
            
            String query = 'SELECT Id, Name,Status__c, Subject__c, Type__c, Account__c, Contact__c, Description__c, Internal_Team_Remarks__c, Closing_Date__c, Ticket_Age__c, Created_By_Name__c, Supporting_Topics__c, '+  
            'Team_Analysis__c, Additional_Details__c FROM Salesforce_Support__c' + ' WHERE OwnerId = \'' + userId + '\' ' + 'AND Status__c != \'Completed\' ' + addQuery + ' ORDER BY CreatedDate DESC';
            System.debug('query ======>' + query);

            List<Salesforce_Support__c> ticketsList = Database.query(query);
            

            List<Map<String, Object>> result = new List<Map<String, Object>>();
            for (Salesforce_Support__c ticket : ticketsList) {
                result.add(new Map<String, Object>{
                    'TicketId' => ticket.Id,
                    'Name' => ticket.Name,
                    'Status' => ticket.Status__c,
                    'Subject' => ticket.Subject__c,
                    'Type' => ticket.Type__c,
                    'AccountId' => ticket.Account__c,
                    'ContactId' => ticket.Contact__c,
                    'Description' => ticket.Description__c,
                    'Remarks' => ticket.Internal_Team_Remarks__c,
                    'ClosingDate' => ticket.Closing_Date__c,
                    'TicketAge' => ticket.Ticket_Age__c,
                    'CreatedBy' => ticket.Created_By_Name__c,
                    'Topics' => ticket.Supporting_Topics__c,
                    'Analysis' => ticket.Team_Analysis__c,
                    'AdditionalDetails' => ticket.Additional_Details__c
                });
            }
            
            MobileApp_Wrapper.setResponses(200, 'Success', result);
        } catch (Exception e) {
            System.debug('Error ====> ' + e.getMessage() + ' at line number =====> ' + e.getLineNumber());
            MobileApp_Wrapper.setResponses(500, 'Error: ' + e.getMessage(), null);
        }
    }
}