force-app/main/default/objects/Course_Master__c/Course_Master__c.object-meta.xml
<CustomObject>
    <label>Course Master</label>
    <nameField>
        <displayFormat>CM-{00000}</displayFormat>
        <label>Course Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Master__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Course Master</relationshipLabel>
    <relationshipName>Course_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Course_Code__c.field-meta.xml
<CustomField>
    <fullName>Course_Code__c</fullName>
    <label>Course Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <label>Course Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Course_Type__c.field-meta.xml
<CustomField>
    <fullName>Course_Type__c</fullName>
    <label>Course Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/Duration_In_Months__c.field-meta.xml
<CustomField>
    <fullName>Duration_In_Months__c</fullName>
    <label>Duration (In Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/IsFavourite__c.field-meta.xml
<CustomField>
    <fullName>IsFavourite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsFavourite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course_Master__c/fields/order_number__c.field-meta.xml
<CustomField>
    <fullName>order_number__c</fullName>
    <label>order number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/Course_Module__c.object-meta.xml
<CustomObject>
    <label>Course Module</label>
    <nameField>
        <displayFormat>CM-{00000}</displayFormat>
        <label>Course Module Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Module</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Module__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Course Module</relationshipLabel>
    <relationshipName>Course_Module</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Course_Master__c.field-meta.xml
<CustomField>
    <fullName>Course_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Master</label>
    <referenceTo>Course_Master__c</referenceTo>
    <relationshipLabel>Course Module</relationshipLabel>
    <relationshipName>Course_Module</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Module_Number__c.field-meta.xml
<CustomField>
    <fullName>Module_Number__c</fullName>
    <label>Module Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course_Sessions__c/Course_Sessions__c.object-meta.xml
<CustomObject>
    <label>Course Sessions</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Course Sessions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Sessions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Course Sessions</relationshipLabel>
    <relationshipName>Course_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Sessions__c/fields/Course_Module__c.field-meta.xml
<CustomField>
    <fullName>Course_Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Module</label>
    <referenceTo>Course_Module__c</referenceTo>
    <relationshipLabel>Course Sessions</relationshipLabel>
    <relationshipName>Course_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Sessions__c/fields/Session_Name__c.field-meta.xml
<CustomField>
    <fullName>Session_Name__c</fullName>
    <label>Session Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Sessions__c/fields/Session_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Session_Sequence__c</fullName>
    <label>Session Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course_Sessions__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <formula>&apos;https://www.youtube.com/embed/&apos;+mid(Video_Link__c,33,20)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Questions__c/Questions__c.object-meta.xml
<CustomObject>
    <label>CheckList Response</label>
    <nameField>
        <displayFormat>QN-{000}</displayFormat>
        <label>Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CheckList Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Questions__c/fields/Question_Name__c.field-meta.xml
<CustomField>
    <fullName>Question_Name__c</fullName>
    <label>Question</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Questions__c/fields/Question_Options__c.field-meta.xml
<CustomField>
    <fullName>Question_Options__c</fullName>
    <label>Question Options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2005</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>To be the global leader in electronics retail.</fullName>
            </value>
            <value>
                <fullName>To provide a wide range of fashionable bottom wear for women.</fullName>
            </value>
            <value>
                <fullName>To innovate in sustainable energy solutions.</fullName>
            </value>
            <value>
                <fullName>To offer the best coffee in town.</fullName>
            </value>
            <value>
                <fullName>Competitive pricing</fullName>
            </value>
            <value>
                <fullName>Technological innovation</fullName>
            </value>
            <value>
                <fullName>Customer-centric service</fullName>
            </value>
            <value>
                <fullName>Fast shipping</fullName>
            </value>
            <value>
                <fullName>Opening their 1000th store</fullName>
            </value>
            <value>
                <fullName>Launching their first overseas branch</fullName>
            </value>
            <value>
                <fullName>First participation in a major fashion week</fullName>
            </value>
            <value>
                <fullName>Reaching 1 million sales in a single year</fullName>
            </value>
            <value>
                <fullName>Speed</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Luxury</fullName>
            </value>
            <value>
                <fullName>Sustainability</fullName>
            </value>
            <value>
                <fullName>Check the email for any corporate communications.</fullName>
            </value>
            <value>
                <fullName>Take a quick break before the rush begins.</fullName>
            </value>
            <value>
                <fullName>Perform a safety check and ensure all emergency exits are clear.</fullName>
            </value>
            <value>
                <fullName>Turn on the music system to set up the day&apos;s ambiance.</fullName>
            </value>
            <value>
                <fullName>Always stock the least popular items at the front.</fullName>
            </value>
            <value>
                <fullName>Use first in, first out (FIFO) method to keep inventory fresh.</fullName>
            </value>
            <value>
                <fullName>Only restock items when completely out of stock.</fullName>
            </value>
            <value>
                <fullName>Ignore expiration dates as long as the product looks fine.</fullName>
            </value>
            <value>
                <fullName>Once a year.</fullName>
            </value>
            <value>
                <fullName>Every month.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Questions__c/fields/Question_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Question_Sequence__c</fullName>
    <label>Question Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Questions__c/fields/Quiz_Template__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz Template</label>
    <referenceTo>Quiz_Template__c</referenceTo>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_Response__c/Quiz_Response__c.object-meta.xml
<CustomObject>
    <label>Response Line Items</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Quiz Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Response__c/fields/Course_Sessions__c.field-meta.xml
<CustomField>
    <fullName>Course_Sessions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Sessions</label>
    <referenceTo>Course_Sessions__c</referenceTo>
    <relationshipName>Quiz_Response</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_Response__c/fields/Questions__c.field-meta.xml
<CustomField>
    <fullName>Questions__c</fullName>
    <label>Questions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quiz_Response__c/fields/Quiz_Template__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz Template</label>
    <referenceTo>Quiz_Template__c</referenceTo>
    <relationshipName>Quiz_Response</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_Template__c/Quiz_Template__c.object-meta.xml
<CustomObject>
    <label>Quiz Template</label>
    <nameField>
        <label>Quiz Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Template__c/fields/Course_Sessions__c.field-meta.xml
<CustomField>
    <fullName>Course_Sessions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Sessions</label>
    <referenceTo>Course_Sessions__c</referenceTo>
    <relationshipLabel>Quiz Templates</relationshipLabel>
    <relationshipName>Quiz_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Handlecources.cls
public class Handlecources {
    
    @AuraEnabled
    Public Static wrapperHandler getCourseModulesSessions(String courseId){
        set<Id> sessionIds=new set<Id>();
        wrapperHandler WH=new wrapperHandler();
        List<Quiz_Template__c> getAllQuestionTemplatesRelatedTo=new List<Quiz_Template__c>();
        List<Course_Module__c> coursemaster=[Select Id,Module_Name__c,Module_Number__c,Course_Master__c,Course_Master__r.Course_Name__c,
                                             (Select Id,Session_Name__c,Content__c,URL__c From Course_Sessions__r Order by Session_Sequence__c) From Course_Module__c Where Course_Master__c!=null AND Course_Master__c=:courseId AND Course_Master__r.isActive__c=true order By Module_Number__c];

        if(!coursemaster.isEmpty()){
             for(Course_Module__c CM:coursemaster){
                     for(Course_Sessions__c cs:CM.Course_Sessions__r){
                          if(cs.Id!=null){
                                sessionIds.add(cs.Id);
                          }
                    }
             }
        } 

        if(!sessionIds.isEmpty()){
             getAllQuestionTemplatesRelatedTo =[Select Id,Name,Course_Sessions__c,(Select Id,Question_Name__c,Question_Options__c From Questions__r order By Question_Sequence__c) From Quiz_Template__c Where Course_Sessions__c!=null AND Course_Sessions__c=:sessionIds]; 
        } 
        if(!coursemaster.isEmpty()){
              WH.courseModule=coursemaster;
        } 
        if(!getAllQuestionTemplatesRelatedTo.isEmpty()) {
            WH.sessionRelatedQuiz=getAllQuestionTemplatesRelatedTo;
        }                       
        return WH;
    }

    @AuraEnabled
    Public static String createQuizresponse(List<Quiz_Response__c> getAllQuizresponse){

        if(!getAllQuizresponse.isEmpty()){
            upsert getAllQuizresponse;
           
        }
         return 'SUCCESS';
    }

    @AuraEnabled(Cacheable=true)
    Public Static List<Course_Master__c> wiredCourses(){

       List<Course_Master__c> CourseReclist = [SELECT Account__c,Course_Code__c,IsFavourite__c,Course_Name__c,Course_Type__c,CreatedById,CreatedDate,Description__c,Duration_In_Months__c,End_Date__c,Id,IsActive__c,Name,OwnerId,Start_Date__c FROM Course_Master__c where IsActive__c = true order By order_number__c ASC];
       return CourseReclist;
    }
    
    @auraEnabled
    Public static String updateCourseDetails(String courseId, boolean favourite){
        Course_master__c cm = new Course_master__c();
        cm.Id = courseId;
        cm.IsFavourite__c =favourite;
        update cm;
        return 'SUCCESS';
    }

    Public class wrapperHandler{
        @AuraEnabled
        Public List<Course_Module__c> courseModule{get;set;}
        @AuraEnabled
        Public List<Quiz_Template__c> sessionRelatedQuiz{get;set;}
    }

}