force-app/main/default/objects/Customer_Concern__c/Customer_Concern__c.object-meta.xml
<CustomObject>
    <label>Customer Concern</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Customer Concern Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Concerns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Concern__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Customer Concerns</relationshipLabel>
    <relationshipName>Customer_Concerns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Concern__c/fields/Case_Category__c.field-meta.xml
<CustomField>
    <fullName>Case_Category__c</fullName>
    <label>Case Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Department__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Parts</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Amenities/Facilities</fullName>
            </value>
            <value>
                <fullName>Service Quality</fullName>
            </value>
            <value>
                <fullName>Service Experience</fullName>
            </value>
            <value>
                <fullName>Sales Concerns</fullName>
            </value>
            <value>
                <fullName>Merchandise Related</fullName>
            </value>
            <value>
                <fullName>Returns and Refunds</fullName>
            </value>
            <value>
                <fullName>Customer Care Issues</fullName>
            </value>
            <value>
                <fullName>Service Request</fullName>
            </value>
            <value>
                <fullName>General Query</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Concern__c/fields/Closed_Resolution__c.field-meta.xml
<CustomField>
    <fullName>Closed_Resolution__c</fullName>
    <label>Closed Resolution</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Concern__c/fields/Concerns__c.field-meta.xml
<CustomField>
    <fullName>Concerns__c</fullName>
    <label>Concerns</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Case_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Belt</fullName>
            </value>
            <value>
                <fullName>Brakes</fullName>
            </value>
            <value>
                <fullName>Bootlamp</fullName>
            </value>
            <value>
                <fullName>Centre Stand</fullName>
            </value>
            <value>
                <fullName>Charger</fullName>
            </value>
            <value>
                <fullName>Crash Guard</fullName>
            </value>
            <value>
                <fullName>Display</fullName>
            </value>
            <value>
                <fullName>Foot Peg LH</fullName>
            </value>
            <value>
                <fullName>HeadLamp</fullName>
            </value>
            <value>
                <fullName>Horn</fullName>
            </value>
            <value>
                <fullName>Indicator</fullName>
            </value>
            <value>
                <fullName>Lockset</fullName>
            </value>
            <value>
                <fullName>Mode</fullName>
            </value>
            <value>
                <fullName>Pannel</fullName>
            </value>
            <value>
                <fullName>Performance</fullName>
            </value>
            <value>
                <fullName>PRCD</fullName>
            </value>
            <value>
                <fullName>Range</fullName>
            </value>
            <value>
                <fullName>Vehicle Power Cut OFF</fullName>
            </value>
            <value>
                <fullName>Throttle</fullName>
            </value>
            <value>
                <fullName>Side stand</fullName>
            </value>
            <value>
                <fullName>Steering</fullName>
            </value>
            <value>
                <fullName>Suspension</fullName>
            </value>
            <value>
                <fullName>Switch Gear LH</fullName>
            </value>
            <value>
                <fullName>Switch Gear RH</fullName>
            </value>
            <value>
                <fullName>Tailamp</fullName>
            </value>
            <value>
                <fullName>Tyre</fullName>
            </value>
            <value>
                <fullName>USB</fullName>
            </value>
            <value>
                <fullName>Wheels</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Concern__c/fields/Subconcerns__c.field-meta.xml
<CustomField>
    <fullName>Subconcerns__c</fullName>
    <label>Subconcerns</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Concerns__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Visor Damage</fullName>
            </value>
            <value>
                <fullName>Visor Fitment</fullName>
            </value>
            <value>
                <fullName>Floor Mat Damage</fullName>
            </value>
            <value>
                <fullName>Floor Mat Fitment</fullName>
            </value>
            <value>
                <fullName>Ladies Footrest Damage</fullName>
            </value>
            <value>
                <fullName>Ladies Footrest Fitment</fullName>
            </value>
            <value>
                <fullName>Seat Replacement</fullName>
            </value>
            <value>
                <fullName>Seat Cover Replace</fullName>
            </value>
            <value>
                <fullName>Seat Cover Fitment</fullName>
            </value>
            <value>
                <fullName>Mobile mount Damage</fullName>
            </value>
            <value>
                <fullName>Mobile mount Adjustment</fullName>
            </value>
            <value>
                <fullName>Mobile mount Fitment</fullName>
            </value>
            <value>
                <fullName>LH Mirror Damage</fullName>
            </value>
            <value>
                <fullName>LH Mirror Fitment</fullName>
            </value>
            <value>
                <fullName>RH Mirror Damage</fullName>
            </value>
            <value>
                <fullName>RH Mirror Fitment</fullName>
            </value>
            <value>
                <fullName>Panier Mount LH Damage</fullName>
            </value>
            <value>
                <fullName>Panier Mount LH Fitment</fullName>
            </value>
            <value>
                <fullName>Panier Mount RH Damage</fullName>
            </value>
            <value>
                <fullName>Panier Mount RH Fitment</fullName>
            </value>
            <value>
                <fullName>Belt Noise</fullName>
            </value>
            <value>
                <fullName>Snap</fullName>
            </value>
            <value>
                <fullName>Brakes Stuck</fullName>
            </value>
            <value>
                <fullName>Brakes Noise</fullName>
            </value>
            <value>
                <fullName>Sponginess</fullName>
            </value>
            <value>
                <fullName>Master Cylinder oil leak</fullName>
            </value>
            <value>
                <fullName>Caliper oil leak</fullName>
            </value>
            <value>
                <fullName>Disc bent FR</fullName>
            </value>
            <value>
                <fullName>Disc bent RR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Concern__c/fields/VOC__c.field-meta.xml
<CustomField>
    <fullName>VOC__c</fullName>
    <label>VOC</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CustomerFeedbackController.cls
public class CustomerFeedbackController {
    
    public Case currentCase{get; set;}
    public Vehicle caseVehicle{get; set;}
    //public List<Customer_Feedback__c> customerFeedbacks{get; set;}
    public List<Customer_Concern__c> customerFeedbacks{get; set;}
    public Account owner{get; set;}
    public List<AssetMilestone> assetMilestones {get; set;}
    public Date deliverDate{get;set;}
    public Date purchaseDate{get;set;}
    public String perfectDeliverTime{get;set;}
    public Boolean hasError { get; set; }
    public String VehicleReceviedBy {get; set;}
    public String caseCurrentDate {get; set;} 
    public Datetime perfectDeliverDate {get; set;} 
    public Date VehiclePurchaseDate {get; set;} 
    //public String formattedAddress { get; set; }
    
    public CustomerFeedbackController(ApexPages.StandardController controller) {
        String caseId = ApexPages.currentPage().getParameters().get('id');
        getCommunityFeedbackUrl(caseId);//added by Aniket
        hasError = false;
        
        try {
            currentCase = [SELECT Id,CaseNumber, ContactId, AccountId, Status, Subject, Priority, Description, ContactPhone, Case_Category__c, Case_Type__c, vehicle__c, CreatedDate from Case where Id = :caseId LIMIT 1];
            system.debug('currentCase===='+currentCase);
            if(currentCase != NULL) {
                caseCurrentDate = formattedCreatedDate(currentCase.CreatedDate);
                if(currentCase.vehicle__c != NULL) {
                    caseVehicle = [SELECT id,VehicleIdentificationNumber, VehicleRegistrationNumber, LastOdometerReading, Purchased_Date__c, CurrentOwnerId, Dealer__r.name, Dealer__r.ShippingCity, Dealer__r.ShippingState,Dealer__r.Center_Code__c   from vehicle where id =: currentCase.vehicle__c limit 1];
                    system.debug('caseVehicle===='+caseVehicle);
                    
                    owner = [SELECT id, Name, ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode, ShippingCountry, Phone from Account where Id =: caseVehicle.CurrentOwnerId];
                    
                    customerFeedbacks = [SELECT VOC__c, Closed_Resolution__c,Concerns__c,Subconcerns__c  from Customer_Concern__c where Case__c =: currentCase.Id];   
                    system.debug('customerFeedbacks===='+customerFeedbacks);
                    assetMilestones = [SELECT id, VehicleId,Vehicle.Purchased_Date__c, MilestoneType, MilestoneDate, Delivery_Date__c,Vehicle_Received_By__c  from AssetMilestone  where  VehicleId =: caseVehicle.Id]; //where (MilestoneType = 'Customer Delivery' or MilestoneType = 'Sold')
                    system.debug('assetMilestones===='+assetMilestones);
                    
                    if(assetMilestones.size() > 0) {
                        for(AssetMilestone assetMile : assetMilestones) {
                            if(assetMile.MilestoneType == 'Customer Delivery') {
                                deliverDate = assetMile.MilestoneDate;
                                perfectDeliverDate = assetMile.Delivery_Date__c;
                                perfectDeliverTime = formattedPerfectDeliverTime(assetMile.Delivery_Date__c);
                                VehicleReceviedBy = assetMile.Vehicle_Received_By__c;
                                VehiclePurchaseDate = assetMile.Vehicle.Purchased_Date__c;
                                system.debug('VehiclePurchaseDate==='+VehiclePurchaseDate);
                            }else if(assetMile.MilestoneType == 'Sold') {
                                purchaseDate = assetMile.MilestoneDate;
                            }
                        }
                    } else {
                        //hasError = true;
                        //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No Record Found.'));
                    }
                } else {
                    hasError = True;
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Current case does not contain any vehicle.'));
                }
                
            }else{
                hasError = true;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Something went wrong. Please contact your administrator.'));
            }
        } catch (Exception e) {
            hasError = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }
    }
    
    public String formattedPerfectDeliverTime(Datetime perfectDeliverTime) {
        return convertToUserTimezone(perfectDeliverTime, 'HH:mm:ss');
    }
    
    public String formattedCreatedDate(Datetime caseDate) {
        return convertToUserTimezone(caseDate, 'd MMMM yyyy HH:mm:ss');
    }
    
    public String convertToUserTimezone(Datetime gmtDatetime, String format) {
        if (gmtDatetime == null) {
            return 'N/A'; // Return a default value if datetime is null
        }
        
        TimeZone tz = UserInfo.getTimeZone();
        
        String formattedDate = gmtDatetime.format(format, tz.getID());
        System.debug(formattedDate);
        return formattedDate;
    }
    
    //added by Aniket
    @AuraEnabled
    public static String getCommunityFeedbackUrl(Id caseId) {
        System.debug('⚡ Called getCommunityFeedbackUrl with caseId = ' + caseId);
        
        String path = '/autocloudSite/apex/CustomerFeedbackForm?id=' + caseId;
        String baseUrl = URL.getOrgDomainUrl().toExternalForm();
        String fullUrl = baseUrl + path;
        
        System.debug('🔗 Full Community URL: ' + fullUrl);
        return fullUrl;
    }
    
    
    
    /*public static String formatAddress(String shippingStreet, String shippingCity, String shippingPostalCode, String shippingState, String shippingCountry) {
String formattedAddress = '';
Integer maxLength = 20;

// Split the shipping street into lines with maximum 30 characters each
List<String> streetLines = new List<String>();
while (shippingStreet.length() > maxLength) {
streetLines.add(shippingStreet.substring(0, maxLength));
shippingStreet = shippingStreet.substring(maxLength);
}
streetLines.add(shippingStreet); // Add the remaining part

// Concatenate the street lines with <br/> and add city, postal code, state, and country
formattedAddress = String.join(streetLines, '<br/>') + '<br/>' + shippingCity + ' ' + shippingPostalCode + ', ' + shippingState + ', ' + shippingCountry;

return formattedAddress;
}*/
    
}