force-app/main/default/objects/Customer_Concern__c/Customer_Concern__c.object-meta.xml
<CustomObject>
    <label>Customer Concern</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Customer Concern Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Concerns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Concern__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Customer Concerns</relationshipLabel>
    <relationshipName>Customer_Concerns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CustomerConcernsInlineEditControllerTest.cls
@isTest
public class CustomerConcernsInlineEditControllerTest {

    @isTest
    static void testCustomerConcernListSuccess() {
        Case testCase = new Case(
            Subject = 'Test Case',
            Status = 'New',
            Origin = 'Phone'
        );
        insert testCase;

        Customer_Concern__c cc1 = new Customer_Concern__c( Case__c = testCase.Id);
        Customer_Concern__c cc2 = new Customer_Concern__c( Case__c = testCase.Id);
        insert new List<Customer_Concern__c>{ cc1, cc2 };

        Test.startTest();
        	CustomerConcernsInlineEditController.customerConcernList(testCase.Id);
        Test.stopTest();
    }

    @isTest
    static void testCustomerConcernListCatchBlock() {
        Test.startTest();
            CustomerConcernsInlineEditController.customerConcernList(null);
        Test.stopTest();
    }
}