force-app/main/default/objects/Customer_Concern__c/Customer_Concern__c.object-meta.xml
<CustomObject>
    <label>Customer Concern</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Customer Concern Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Concerns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Concern__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Customer Concerns</relationshipLabel>
    <relationshipName>Customer_Concerns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Concern__c/fields/Case_Category__c.field-meta.xml
<CustomField>
    <fullName>Case_Category__c</fullName>
    <label>Case Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Department__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Parts</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Amenities/Facilities</fullName>
            </value>
            <value>
                <fullName>Service Quality</fullName>
            </value>
            <value>
                <fullName>Service Experience</fullName>
            </value>
            <value>
                <fullName>Sales Concerns</fullName>
            </value>
            <value>
                <fullName>Merchandise Related</fullName>
            </value>
            <value>
                <fullName>Returns and Refunds</fullName>
            </value>
            <value>
                <fullName>Customer Care Issues</fullName>
            </value>
            <value>
                <fullName>Service Request</fullName>
            </value>
            <value>
                <fullName>General Query</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Concern__c/fields/Closed_Resolution__c.field-meta.xml
<CustomField>
    <fullName>Closed_Resolution__c</fullName>
    <label>Closed Resolution</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Concern__c/fields/Concerns__c.field-meta.xml
<CustomField>
    <fullName>Concerns__c</fullName>
    <label>Concerns</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Case_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Belt</fullName>
            </value>
            <value>
                <fullName>Brakes</fullName>
            </value>
            <value>
                <fullName>Bootlamp</fullName>
            </value>
            <value>
                <fullName>Centre Stand</fullName>
            </value>
            <value>
                <fullName>Charger</fullName>
            </value>
            <value>
                <fullName>Crash Guard</fullName>
            </value>
            <value>
                <fullName>Display</fullName>
            </value>
            <value>
                <fullName>Foot Peg LH</fullName>
            </value>
            <value>
                <fullName>HeadLamp</fullName>
            </value>
            <value>
                <fullName>Horn</fullName>
            </value>
            <value>
                <fullName>Indicator</fullName>
            </value>
            <value>
                <fullName>Lockset</fullName>
            </value>
            <value>
                <fullName>Mode</fullName>
            </value>
            <value>
                <fullName>Pannel</fullName>
            </value>
            <value>
                <fullName>Performance</fullName>
            </value>
            <value>
                <fullName>PRCD</fullName>
            </value>
            <value>
                <fullName>Range</fullName>
            </value>
            <value>
                <fullName>Vehicle Power Cut OFF</fullName>
            </value>
            <value>
                <fullName>Throttle</fullName>
            </value>
            <value>
                <fullName>Side stand</fullName>
            </value>
            <value>
                <fullName>Steering</fullName>
            </value>
            <value>
                <fullName>Suspension</fullName>
            </value>
            <value>
                <fullName>Switch Gear LH</fullName>
            </value>
            <value>
                <fullName>Switch Gear RH</fullName>
            </value>
            <value>
                <fullName>Tailamp</fullName>
            </value>
            <value>
                <fullName>Tyre</fullName>
            </value>
            <value>
                <fullName>USB</fullName>
            </value>
            <value>
                <fullName>Wheels</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Concern__c/fields/Subconcerns__c.field-meta.xml
<CustomField>
    <fullName>Subconcerns__c</fullName>
    <label>Subconcerns</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Concerns__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Visor Damage</fullName>
            </value>
            <value>
                <fullName>Visor Fitment</fullName>
            </value>
            <value>
                <fullName>Floor Mat Damage</fullName>
            </value>
            <value>
                <fullName>Floor Mat Fitment</fullName>
            </value>
            <value>
                <fullName>Ladies Footrest Damage</fullName>
            </value>
            <value>
                <fullName>Ladies Footrest Fitment</fullName>
            </value>
            <value>
                <fullName>Seat Replacement</fullName>
            </value>
            <value>
                <fullName>Seat Cover Replace</fullName>
            </value>
            <value>
                <fullName>Seat Cover Fitment</fullName>
            </value>
            <value>
                <fullName>Mobile mount Damage</fullName>
            </value>
            <value>
                <fullName>Mobile mount Adjustment</fullName>
            </value>
            <value>
                <fullName>Mobile mount Fitment</fullName>
            </value>
            <value>
                <fullName>LH Mirror Damage</fullName>
            </value>
            <value>
                <fullName>LH Mirror Fitment</fullName>
            </value>
            <value>
                <fullName>RH Mirror Damage</fullName>
            </value>
            <value>
                <fullName>RH Mirror Fitment</fullName>
            </value>
            <value>
                <fullName>Panier Mount LH Damage</fullName>
            </value>
            <value>
                <fullName>Panier Mount LH Fitment</fullName>
            </value>
            <value>
                <fullName>Panier Mount RH Damage</fullName>
            </value>
            <value>
                <fullName>Panier Mount RH Fitment</fullName>
            </value>
            <value>
                <fullName>Belt Noise</fullName>
            </value>
            <value>
                <fullName>Snap</fullName>
            </value>
            <value>
                <fullName>Brakes Stuck</fullName>
            </value>
            <value>
                <fullName>Brakes Noise</fullName>
            </value>
            <value>
                <fullName>Sponginess</fullName>
            </value>
            <value>
                <fullName>Master Cylinder oil leak</fullName>
            </value>
            <value>
                <fullName>Caliper oil leak</fullName>
            </value>
            <value>
                <fullName>Disc bent FR</fullName>
            </value>
            <value>
                <fullName>Disc bent RR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Concern__c/fields/VOC__c.field-meta.xml
<CustomField>
    <fullName>VOC__c</fullName>
    <label>VOC</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CustomerConcernsInlineEditController.cls
public with sharing class CustomerConcernsInlineEditController {
    @AuraEnabled
    public static List<Customer_Concern__c> customerConcernList(Id caseId) {
        system.debug('caseId: ' + caseId);
        try {
           		return [SELECT Id, Name, Concerns__c,Case_Category__c, Subconcerns__c, VOC__c, Closed_Resolution__c, Case__c  FROM Customer_Concern__c WHERE Case__c = :caseId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}