force-app/main/default/objects/Action_Plan_Template__c/Action_Plan_Template__c.object-meta.xml
<CustomObject>
    <label>Action Plan Template(obsolete)</label>
    <nameField>
        <displayFormat>APT{0000}</displayFormat>
        <label>Action Plan Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Failure_Code__c/Failure_Code__c.object-meta.xml
<CustomObject>
    <label>Failure Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Failure Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Failure_Code__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <label>Sample Required</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Failure_Code__c/fields/FPV_Validation__c.field-meta.xml
<CustomField>
    <fullName>FPV_Validation__c</fullName>
    <formula>Name+&apos;-&apos;+ TFR_Part_Effect__r.Product__r.Name+&apos;-&apos;+ VIN_Cut_off__r.VIN_Start__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FPV Validation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Failure_Code__c/fields/Sample_Collected__c.field-meta.xml
<CustomField>
    <fullName>Sample_Collected__c</fullName>
    <label>Sample Collected</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Failure_Code__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>TFR Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Activate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Failure_Code__c/fields/TFR_Labour_Effect__c.field-meta.xml
<CustomField>
    <fullName>TFR_Labour_Effect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TFR Labour Effect</label>
    <referenceTo>TFR_Labour_Effect__c</referenceTo>
    <relationshipLabel>Failure Code</relationshipLabel>
    <relationshipName>Failure_Code</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Failure_Code__c/fields/TFR_Part_Effect__c.field-meta.xml
<CustomField>
    <fullName>TFR_Part_Effect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TFR Part Effect</label>
    <referenceTo>TFR_Part_Effect__c</referenceTo>
    <relationshipLabel>Failure Code</relationshipLabel>
    <relationshipName>Failure_Code</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Failure_Code__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Part</fullName>
            </value>
            <value>
                <fullName>Labour</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Failure_Code__c/fields/VIN_Cut_off__c.field-meta.xml
<CustomField>
    <fullName>VIN_Cut_off__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VIN Cut off</label>
    <referenceTo>TFR__c</referenceTo>
    <relationshipLabel>Failure Code</relationshipLabel>
    <relationshipName>Failure_Code</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Failure_Code__c/fields/VIN_Cut_off_No__c.field-meta.xml
<CustomField>
    <fullName>VIN_Cut_off_No__c</fullName>
    <formula>VIN_Cut_off__r.VIN_Start__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VIN Cut off No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Required_Labour__c/Required_Labour__c.object-meta.xml
<CustomObject>
    <label>Required Labour</label>
    <nameField>
        <displayFormat>RLN{0000}</displayFormat>
        <label>Required Labour Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Required Labours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Required_Labour__c/fields/Action_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan_Template__c</fullName>
    <label>Action Plan Template</label>
    <referenceTo>ActionPlanTemplate</referenceTo>
    <relationshipLabel>Required Labours</relationshipLabel>
    <relationshipName>Required_Labours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Required_Labour__c/fields/Code_Set__c.field-meta.xml
<CustomField>
    <fullName>Code_Set__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Code Set</label>
    <referenceTo>CodeSet</referenceTo>
    <relationshipLabel>Required Labours</relationshipLabel>
    <relationshipName>Required_Labours</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Required_Product__c/Required_Product__c.object-meta.xml
<CustomObject>
    <label>Required Product</label>
    <nameField>
        <displayFormat>RP{0000}</displayFormat>
        <label>Required Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Required Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Required_Product__c/fields/Action_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan_Template__c</fullName>
    <label>Action Plan Template</label>
    <referenceTo>ActionPlanTemplate</referenceTo>
    <relationshipLabel>Required Products</relationshipLabel>
    <relationshipName>Required_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Required_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Required Products</relationshipLabel>
    <relationshipName>Required_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR__c/TFR__c.object-meta.xml
<CustomObject>
    <label>VIN Cut off</label>
    <nameField>
        <displayFormat>VINCOFF-{000000}</displayFormat>
        <label>TFR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VIN Cut off</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TFR__c/fields/VIN_Start__c.field-meta.xml
<CustomField>
    <fullName>VIN_Start__c</fullName>
    <label>VIN Start</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TFR_Labour_Effect__c/TFR_Labour_Effect__c.object-meta.xml
<CustomObject>
    <label>TFR Labour Effect</label>
    <nameField>
        <displayFormat>TFREL-{000000}</displayFormat>
        <label>TFR Labour Effect Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TFR Labour Effects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TFR_Labour_Effect__c/fields/Code_Set__c.field-meta.xml
<CustomField>
    <fullName>Code_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Code Set</label>
    <referenceTo>CodeSet</referenceTo>
    <relationshipLabel>TFR Labour Effects</relationshipLabel>
    <relationshipName>TFR_Labour_Effects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Labour_Effect__c/fields/Failure_Code__c.field-meta.xml
<CustomField>
    <fullName>Failure_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Failure Code</label>
    <referenceTo>Failure_Code__c</referenceTo>
    <relationshipLabel>TFR Labour Effects</relationshipLabel>
    <relationshipName>TFR_Labour_Effects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Labour_Effect__c/fields/TFR__c.field-meta.xml
<CustomField>
    <fullName>TFR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VIN Cut off</label>
    <referenceTo>TFR__c</referenceTo>
    <relationshipLabel>TFR Labour Effects</relationshipLabel>
    <relationshipName>TFR_Labour_Effects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Labour_Effect__c/fields/VIN_Cut_off__c.field-meta.xml
<CustomField>
    <fullName>VIN_Cut_off__c</fullName>
    <formula>TFR__r.VIN_Start__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VIN Cut off</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TFR_Part_Effect__c/TFR_Part_Effect__c.object-meta.xml
<CustomObject>
    <label>TFR Causal Part</label>
    <nameField>
        <displayFormat>TFREP-{000000}</displayFormat>
        <label>TFR Part Effect Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TFR Causal Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TFR_Part_Effect__c/fields/Failure_Code__c.field-meta.xml
<CustomField>
    <fullName>Failure_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Failure Code</label>
    <referenceTo>Failure_Code__c</referenceTo>
    <relationshipName>TFR_Part_Effects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Part_Effect__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>TFR Part Effects</relationshipLabel>
    <relationshipName>TFR_Part_Effects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Part_Effect__c/fields/TFR__c.field-meta.xml
<CustomField>
    <fullName>TFR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TFR</label>
    <referenceTo>TFR__c</referenceTo>
    <relationshipLabel>TFR Part Effects</relationshipLabel>
    <relationshipName>TFR_Part_Effects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/TFR_Sample__c.object-meta.xml
<CustomObject>
    <label>TFR Sample</label>
    <nameField>
        <displayFormat>TFRSMP-{00000000}</displayFormat>
        <label>TFR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TFR_Sample</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TFR_Sample__c/fields/Failure_Code__c.field-meta.xml
<CustomField>
    <fullName>Failure_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Failure Code</label>
    <referenceTo>Failure_Code__c</referenceTo>
    <relationshipName>TFR_Sample</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Job_Card__c.field-meta.xml
<CustomField>
    <fullName>Job_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Card</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>TFR_Sample</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/TFR__c.field-meta.xml
<CustomField>
    <fullName>TFR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TFR</label>
    <referenceTo>TFR__c</referenceTo>
    <relationshipName>TFR_Sample</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TFRManagement.cls
public without sharing class TFRManagement {
    
    @AuraEnabled(cacheable=true)
    public static List<Failure_Code__c> getFailureCodes() {
        return [
            SELECT Id, Name, Batch_Size__c, Sample_Collected__c, Is_Active__c, 
            TFR_Part_Effect__c, TFR_Part_Effect__r.Product__r.Name, 
            TFR_Part_Effect__r.Product__r.ProductCode, TFR_Labour_Effect__c,
            TFR_Labour_Effect__r.Code_Set__r.Name, TFR_Labour_Effect__r.Code_Set__r.Code,
            VIN_Cut_off__c, VIN_Cut_off__r.Is_Active__c, VIN_Cut_off__r.VIN_Start__c,
            CreatedBy.Name, CreatedDate, FPV_Validation__c, Type__c
            FROM Failure_Code__c
            WHERE (TFR_Part_Effect__c != NULL OR TFR_Labour_Effect__c != NULL)
            ORDER BY CreatedDate DESC
            LIMIT 1000
        ];
    }
    
    @AuraEnabled
    public static void deleteFailureCode(Id recordId) {
        delete [SELECT Id FROM Failure_Code__c WHERE Id = :recordId];
    }
    
    @AuraEnabled
    public static TFRValidationResult checkTFRValidation(String VINno, String FailureCodeId) {
        try {
            // First, check if failure code exists regardless of VIN
            Failure_Code__c fc;
            
            
            fc = [SELECT Id, Name, Is_Active__c, TFR_Part_Effect__c, 
                  TFR_Part_Effect__r.TFR__r.VIN_Start__c,VIN_Cut_off_No__c,
                  TFR_Part_Effect__r.Product__r.ProductCode,Status__c
                  FROM Failure_Code__c 
                  WHERE Id = :FailureCodeId limit 1];
            
            
            // If no VIN provided, just check if failure code is active
            if (String.isBlank(VINno)) {
                return new TFRValidationResult(
                    fc.Is_Active__c, 
                    false,
                    fc.Is_Active__c ? 'Active failure code' : 'Inactive failure code'
                );
            }
            
            // If VIN is provided, perform VIN-based validation
            String vinCutoff;
            
            //vinCutoff = fc.TFR_Part_Effect__c != null ? fc.TFR_Part_Effect__r.TFR__r.VIN_Start__c : null;
            vinCutoff = fc.VIN_Cut_off_No__c;
            if (vinCutoff != null) {
                VINCutOffManagement.ComparisonResult result = VINCutOffManagement.compareVINFormat(vinCutoff,VINno);
                
                boolean isTFRApplicable=fc.Status__c=='TFR Completed'? false:true;
                return new TFRValidationResult(isTFRApplicable, result.isSuccess && result.resultCode == 1, result.message);
            }
            
            // No VIN cutoff defined for this failure code
            return new TFRValidationResult(true, false, 'No VIN cutoff defined for this failure code');
        } catch (Exception e) {
            system.debug('Error at'+ e.getLineNumber());
            return new TFRValidationResult(false, false, 'Error: ' + e.getMessage());
        }
    }
    
    public class TFRValidationResult {
        @AuraEnabled public Boolean isTFRApplicable;
        @AuraEnabled public Boolean isPostVinCuttoff;
        @AuraEnabled public String message;
        
        public TFRValidationResult(Boolean applicable, Boolean postCutoff, String msg) {
            isTFRApplicable = applicable;
            isPostVinCuttoff = postCutoff;
            message = msg;
        }
    }
    
    @AuraEnabled
    public static actionPlanWrapper VeripartWithActionWithPlanApex(String workOrderId) {
        try {
            actionPlanWrapper prepareData = new actionPlanWrapper();
            Set<String> allAPTids = new Set<String>();
            
            List<ActionPlan> ins = [SELECT Id, Name, To_be_Completed_in_JC__c, 
                                    ActionPlanTemplateVersion.Name, Field_Fix__r.Action_Plan_Template__c
                                    FROM ActionPlan
                                    WHERE Job_Card__c = :workOrderId
                                    AND To_be_Completed_in_JC__c = false];
            
            for (ActionPlan aps : ins) {
                allAPTids.add(aps.Field_Fix__r.Action_Plan_Template__c);
            }
            
            List<Required_Labour__c> RequiredLabours = [SELECT Id, Code_Set__c 
                                                        FROM Required_Labour__c 
                                                        WHERE Action_Plan_Template__c IN :allAPTids];
            
            List<Required_Product__c> RequiredProducts = [SELECT Id, Product__c 
                                                          FROM Required_Product__c 
                                                          WHERE Action_Plan_Template__c IN :allAPTids];
            
            prepareData.RequiredLabours = RequiredLabours;
            prepareData.RequiredProducts = RequiredProducts;
            return prepareData;
        } catch (Exception ex) {
            throw new AuraHandledException('Error in VeripartWithActionWithPlanApex: ' + ex.getMessage());
        }
    }
    
    public class actionPlanWrapper {
        @AuraEnabled public List<Required_Labour__c> RequiredLabours;
        @AuraEnabled public List<Required_Product__c> RequiredProducts;
    }
    
    @future
    public static void addSampleSizeONjcCloser(List<Id> closedJcIds) {
        if (closedJcIds == null || closedJcIds.isEmpty()) {
            return;
        }
        
        // Step 1: Collect Failure_Code__c IDs from related TFR_Sample__c
        Set<Id> failureCodeIds = new Set<Id>();
        for (TFR_Sample__c sample : [
            SELECT Failure_Code__c 
            FROM TFR_Sample__c 
            WHERE Job_Card__c IN :closedJcIds 
            AND Failure_Code__c != null
        ]) {
            failureCodeIds.add(sample.Failure_Code__c);
        }
        
        if (failureCodeIds.isEmpty()) {
            return;
        }
        
        // Step 2: Fetch Failure_Code__c records
        List<Failure_Code__c> failureCodes = [
            SELECT Id, Name, Sample_Collected__c, Batch_Size__c, Status__c
            FROM Failure_Code__c
            WHERE Id IN :failureCodeIds
        ];
        
        // Step 3: Update Sample_Collected__c and Status__c
        for (Failure_Code__c fc : failureCodes) {
            // Increment Sample_Collected__c by 1 for each related Job Card closed
            // (if that’s the logic you want)
            fc.Sample_Collected__c = (fc.Sample_Collected__c == null ? 0 : fc.Sample_Collected__c) + 1;
            
            // If collected samples meet or exceed batch size, mark as closed
            if (fc.Batch_Size__c != null && fc.Sample_Collected__c >= fc.Batch_Size__c) {
                fc.Status__c = 'Closed';
            }
        }
        
        // Step 4: Perform DML update
        if (!failureCodes.isEmpty()) {
            update failureCodes;
        }
    }
    
    
}