force-app/main/default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <label>Comment</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comment__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Order</label>
</CustomObject>

force-app/main/default/classes/MobileApp_EventOpenOppTest.cls
@isTest
public class MobileApp_EventOpenOppTest {
    @isTest
    public static void getTestDrives() {
        User testUser = UtilityTestClass.createSalesManagerUser();
        
        System.runAs(testUser) {
            Account acc = UtilityTestClass.createTestAccount('Test Account', 'C001', 'Test Store', '560076', 'Customer');
            Opportunity opp = UtilityTestClass.createTestOpportunity( 'Test Opportunity', acc.Id, 'RNR', System.today().addDays(30), 10000 );
            Order ord = new Order( Status = 'Activated', OpportunityId = opp.Id, AccountId = acc.Id, OwnerId = testUser.Id, EffectiveDate = Date.today());
            insert ord;
            
            Comment__c comment = new Comment__c(
                Description__c = 'Test Comment',
                Order__c = ord.Id
            );
            insert comment;
            
            MobileApp_Wrapper.MobileApp_LeadTotalLeadsWrapper wrapper = new MobileApp_Wrapper.MobileApp_LeadTotalLeadsWrapper();
            wrapper.UserId = testUser.Id;
            wrapper.FilterDate = 'THIS_MONTH';
            
            RestRequest req = new RestRequest();
            req.requestUri = '/services/apexrest/EventClosedOppAndOrder';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueOf(JSON.serialize(wrapper));
            RestContext.request = req;
            
            RestResponse res = new RestResponse();
            RestContext.response = res;
            
            MobileApp_EventOpenOpp.getTestDrives();
        }
    }

    
    @isTest
    public static void getTestDrives1() {
        User testUser = UtilityTestClass.createSalesManagerUser();
        MobileApp_Wrapper.MobileApp_LeadTotalLeadsWrapper wrapper = new MobileApp_Wrapper.MobileApp_LeadTotalLeadsWrapper();
        wrapper.UserId = testUser.Id;
        wrapper.FilterDate = '2025-03-15';
        wrapper.FilterEndRange = '2025-03-16';    
        RestRequest req = new RestRequest();
        req.requestUri = '/services/apexrest/EventClosedOppAndOrder';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(JSON.serialize(wrapper));
        RestContext.request = req;
        
        RestResponse res = new RestResponse();
        RestContext.response = res;
        
        MobileApp_EventOpenOpp.getTestDrives();
    }
    
}