force-app/main/default/objects/Create_Batch__c/Create_Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <displayFormat>NRDC-{0000}</displayFormat>
        <label>Batch ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Create_Batch__c/fields/Batch_Dispatch_Date__c.field-meta.xml
<CustomField>
    <fullName>Batch_Dispatch_Date__c</fullName>
    <label>Batch Dispatch Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Create_Batch__c/fields/E_Way_Bill_No__c.field-meta.xml
<CustomField>
    <fullName>E_Way_Bill_No__c</fullName>
    <label>E-Way Bill No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Create_Batch__c/fields/Is_GRN_Received__c.field-meta.xml
<CustomField>
    <fullName>Is_GRN_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is GRN Received</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Create_Batch__c/fields/LR_Attachment__c.field-meta.xml
<CustomField>
    <fullName>LR_Attachment__c</fullName>
    <label>LR Attachment</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Create_Batch__c/fields/LR_Number__c.field-meta.xml
<CustomField>
    <fullName>LR_Number__c</fullName>
    <label>LR Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Create_Batch__c/fields/Mode_of_Transport__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport__c</fullName>
    <label>Mode of Transport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Road</fullName>
            </value>
            <value>
                <fullName>Air</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Create_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Create_Batch__c/fields/Transport_Name__c.field-meta.xml
<CustomField>
    <fullName>Transport_Name__c</fullName>
    <label>Transport Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Create_Batch__c/fields/Transporter_ID__c.field-meta.xml
<CustomField>
    <fullName>Transporter_ID__c</fullName>
    <label>Transporter ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Create_Batch__c/fields/Vehicle_No__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_No__c</fullName>
    <label>Vehicle No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryChallanPDF__mdt/DeliveryChallanPDF__mdt.object-meta.xml
<CustomObject>
    <label>DeliveryChallanPDF</label>
    <pluralLabel>DeliveryChallanPDFs</pluralLabel>
</CustomObject>

force-app/main/default/objects/DeliveryChallanPDF__mdt/fields/Bill_From__c.field-meta.xml
<CustomField>
    <fullName>Bill_From__c</fullName>
    <label>Bill From</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryChallanPDF__mdt/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <label>Bill To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryChallanPDF__mdt/fields/CIN__c.field-meta.xml
<CustomField>
    <fullName>CIN__c</fullName>
    <label>CIN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryChallanPDF__mdt/fields/Company_Email__c.field-meta.xml
<CustomField>
    <fullName>Company_Email__c</fullName>
    <label>Company Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/DeliveryChallanPDF__mdt/fields/Company_Phone__c.field-meta.xml
<CustomField>
    <fullName>Company_Phone__c</fullName>
    <label>Company Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/DeliveryChallanPDF__mdt/fields/Company_Website__c.field-meta.xml
<CustomField>
    <fullName>Company_Website__c</fullName>
    <label>Company Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/DeliveryChallanPDF__mdt/fields/CompanyName__c.field-meta.xml
<CustomField>
    <fullName>CompanyName__c</fullName>
    <label>CompanyName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryChallanPDF__mdt/fields/Factory_Address__c.field-meta.xml
<CustomField>
    <fullName>Factory_Address__c</fullName>
    <label>Factory Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryChallanPDF__mdt/fields/Former_Address__c.field-meta.xml
<CustomField>
    <fullName>Former_Address__c</fullName>
    <label>Former Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryChallanPDF__mdt/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <label>GST</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryChallanPDF__mdt/fields/PartA__c.field-meta.xml
<CustomField>
    <fullName>PartA__c</fullName>
    <label>PartA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryChallanPDF__mdt/fields/Registered_Office__c.field-meta.xml
<CustomField>
    <fullName>Registered_Office__c</fullName>
    <label>Registered Office</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryChallanPDF__mdt/fields/Small_CName__c.field-meta.xml
<CustomField>
    <fullName>Small_CName__c</fullName>
    <label>Small CName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchRecordControllerPDFTest.cls
@isTest
public class BatchRecordControllerPDFTest  {
    
    @isTest
    static void testfetchDCCustomMetaDetails() {
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        
        Create_Batch__c batch = new Create_Batch__c(
            Status__c = 'New', 
            Is_GRN_Received__c = false, 
            Batch_Dispatch_Date__c = Date.today(), 
            E_Way_Bill_No__c = 'E-QAY-00029',
            Vehicle_No__c = 'KA-0001', 
            Transporter_ID__c = 'TR-001', 
            Transport_Name__c = 'defg',  
            LR_Attachment__c ='https://river.com', 
            LR_Number__c = 'defsgb',
            Mode_of_Transport__c = 'Road'
        );
        insert batch;
        
        Id pricebookId = Test.getStandardPricebookId();
        Pricebook2 standardPricebook = new Pricebook2(
            Id = pricebookId,
            State__c = 'Karnataka',
            IsActive = true
        );
        update standardPricebook;
        
        Product2 product1 = new Product2(Name = 'Test Product 1', IsActive = true, ProductCode = 'SDFGH3456', HSN_Code__c = 'FGHJK367', Type__c = 'Parts');
        insert product1;
        
        PricebookEntry pricebookEntry1 = new PricebookEntry(Pricebook2Id = standardPricebook.Id, Product2Id = product1.Id, UnitPrice = 100, IsActive = true);
        insert pricebookEntry1;
        
        WorkOrder workOrder = new WorkOrder(AccountId = acc.Id, Status = 'New', Subject = 'Test Work Order');
        insert workOrder;
        
        WorkOrderLineItem workOrderLineItem1 = new WorkOrderLineItem(
            WorkOrderId = workOrder.Id,  
            Quantity = 2, 
            UnitPrice = 120,  
            PricebookEntryId = pricebookEntry1.Id 
        );
        insert workOrderLineItem1;
        
        OrgWideEmailAddress owea = [SELECT Id, DisplayName 
                                        FROM OrgWideEmailAddress 
                                        WHERE DisplayName = :System.Label.OrgWideEmail 
                                        LIMIT 1];
        
       
        DeliveryChallanPDF__mdt d = new DeliveryChallanPDF__mdt();
        d.Bill_From__c='987';
        d.Bill_To__c='0986';
        d.CIN__c='98';
        d.Company_Email__c='a@test.com';
        d.CompanyName__c='987';
        d.Company_Phone__c='0987654321';
        d.Company_Website__c='https://www.example.com';
        d.Factory_Address__c='987';
        d.Former_Address__c='097';
        d.GST__c='098';
        d.PartA__c='09';
        d.Registered_Office__c='098';
        d.Small_CName__c='098';
        Claim claim = new Claim(Name='Test Claim', Create_Batch__c=batch.Id, AccountId = acc.Id);
        insert claim;
        
        // Create test ClaimItem
        ClaimItem claimItem = new ClaimItem(Name='Test Claim Item', ClaimId=claim.Id, Claim_Type__c='Labour', Status__c='Approved', FaultDate= System.now(),Part__c =workOrderLineItem1.id  );
        insert claimItem;
        
        PageReference pageRef = Page.BatchDetailPDF; 
        Test.setCurrentPage(pageRef);        
        ApexPages.StandardController standardController = new ApexPages.StandardController(batch);
        BatchRecordControllerPDF controller = new BatchRecordControllerPDF(standardController);
        BatchRecordControllerPDF.saveBatchAsPdf(batch.id,false);
        BatchRecordControllerPDF.saveGenerateReciptAsPdf(batch.id,false);
        ConvertAmountToWords var = new ConvertAmountToWords();
        var.convert();
        ConvertAmountToWords.convert(10000);
    }
    
}