force-app/main/default/objects/Post_Service_Feedback__c/Post_Service_Feedback__c.object-meta.xml
<CustomObject>
    <label>Post Service Feedback</label>
    <nameField>
        <displayFormat>PSF-{00000}</displayFormat>
        <label>PSF No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Service Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Post_Service_Feedback__c/fields/Job_Card__c.field-meta.xml
<CustomField>
    <fullName>Job_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Card</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Post Service Feedbacks</relationshipLabel>
    <relationshipName>Post_Service_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Post_Service_Feedback__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Customer Not Contacted</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>NFA</fullName>
            </value>
            <value>
                <fullName>Ticket Raised</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Software_Version__c/Software_Version__c.object-meta.xml
<CustomObject>
    <label>Software Version</label>
    <nameField>
        <label>Software Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Software Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>TI -{00000}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Job_Card__c.field-meta.xml
<CustomField>
    <fullName>Job_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Card</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Post_Service_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Post_Service_Feedback__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Post Service Feedback</label>
    <referenceTo>Post_Service_Feedback__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complained Resolved via Explaination</fullName>
            </value>
            <value>
                <fullName>Call Later</fullName>
            </value>
            <value>
                <fullName>Appointment Requested</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Re Open</fullName>
            </value>
            <value>
                <fullName>POC Assigned</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Resolution Under Review</fullName>
            </value>
            <value>
                <fullName>Pending Rivision</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Solution not accepted</fullName>
            </value>
            <value>
                <fullName>NFA</fullName>
            </value>
            <value>
                <fullName>Call Back Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TaskHandler_Test.cls
@isTest
public with sharing class TaskHandler_Test {

    @isTest
    public static void testHandleAfterInsert() {

        // Create test data
        Account acc = new Account(Name = 'Test Account', Type='Customer');
        insert acc;

        // Create Contact
        Contact con = new Contact(
            AccountId = acc.Id,    
            FirstName = 'Joey', 
            LastName = 'Shaul',
            Phone = '8967452312');
        insert con;

        // Create Product
        Product2 prod = new Product2(
            Name = 'Test Product', 
            IsActive = true, 
            ProductCode = 'PROd-39784',
            HSN_Code__c = 'HSN-384',
            Type__c = 'Parts');
        insert prod;

        // Create Asset
        Asset ass = new Asset(Name = 'River NX-299', AccountId = acc.Id, Product2Id = prod.Id);
        insert ass;

        // Create Vehicle Defination
        VehicleDefinition vd = new VehicleDefinition();
        vd.Name = 'VD Name 1';
        vd.ProductId = prod.Id; 
        insert vd;

        // Create Software_Version__c
        Software_Version__c sv = new Software_Version__c(Name = 'V1.29');
        insert sv;

        // Create Vehicle
        Vehicle v = new Vehicle();
        v.Name = 'River NX-299';
        v.AssetId = ass.Id;
        v.VehicleDefinitionId = vd.Id;
        v.VehicleIdentificationNumber = '83493HHHGBBB';
        v.Software_Version__c = sv.Id;
        v.Charger_PC_Number__c = 'CHR001';
        insert v;

        // Create WorkOrders
        WorkOrder wo1 = new WorkOrder(
            AccountId = acc.Id,
            ContactId = con.Id,
            Vehicle__c = v.Id,
            Status = 'Completed',
            Completed_Date__c = System.now().addDays(-4),
            Subject = 'Old Completed WO'
        );
        insert wo1;

        // --------------------------------- handleAfterInsert Test Check ---------------------------------
        Post_Service_Feedback__c psf = new Post_Service_Feedback__c();
        psf.Job_Card__c = wo1.Id;
        psf.Status__c = 'Pending';
        insert psf;

        Task psfTask = new Task();
        psfTask.Subject = 'followup-';
        psfTask.Status = 'Pending';
        psfTask.Priority = 'High';
        psfTask.ActivityDate = Date.today();
        psfTask.WhatId = psf.Id;
        insert psfTask;

        // --------------------------------- handleTicketCallCount Test Check ---------------------------------
        Ticket__c newTicket = new Ticket__c(
            Post_Service_Feedback__c = psf.Id,
            Job_Card__c = psf.Job_card__c
        );
        insert newTicket;

        Task ticketTask = new Task();
        ticketTask.Subject = 'ti -';
        ticketTask.Status = 'Pending';
        ticketTask.Priority = 'High';
        ticketTask.ActivityDate = Date.today();
        ticketTask.WhatId = newTicket.Id;
        insert ticketTask;

        // --------------------------------- handleAppointmentCallCount Test Check ---------------------------------


        ServiceAppointment appoint = new ServiceAppointment();
        appoint.Vehicle__c = v.Id;
        appoint.ParentRecordId = wo1.Id;
        insert appoint;

        Task appointTask = new Task();
        appointTask.Subject = '- call back request';
        appointTask.Status = 'Pending';
        appointTask.Priority = 'High';
        appointTask.ActivityDate = Date.today();
        appointTask.WhatId = appoint.Id;
        insert appointTask;
        
        TaskHandler.mytest();

    }

    
    
    
}