force-app/main/default/objects/Pre_Delivery_Inspection__c/Pre_Delivery_Inspection__c.object-meta.xml
<CustomObject>
    <label>Pre Delivery Inspection</label>
    <nameField>
        <displayFormat>PDI-{0000}</displayFormat>
        <label>Pre Delivery Inspection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre Delivery Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pre_Delivery_Inspection__c/fields/Attribute__c.field-meta.xml
<CustomField>
    <fullName>Attribute__c</fullName>
    <label>Attribute</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Documentation/ Hardware verification</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Decals</fullName>
            </value>
            <value>
                <fullName>Aesthetic Checks</fullName>
            </value>
            <value>
                <fullName>Firmware Checks</fullName>
            </value>
            <value>
                <fullName>Dashboard Functionality</fullName>
            </value>
            <value>
                <fullName>Lockset Functionality</fullName>
            </value>
            <value>
                <fullName>Charging Functionality</fullName>
            </value>
            <value>
                <fullName>Test Ride (3km)</fullName>
            </value>
            <value>
                <fullName>Presets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pre_Delivery_Inspection__c/fields/Parameter__c.field-meta.xml
<CustomField>
    <fullName>Parameter__c</fullName>
    <label>Parameter</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Pre_Delivery_Inspection_Item__c/Pre_Delivery_Inspection_Item__c.object-meta.xml
<CustomObject>
    <label>Pre Delivery Inspection Item</label>
    <nameField>
        <displayFormat>PDI-Item-{0000}</displayFormat>
        <label>Pre Delivery Inspection Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre Delivery Inspection Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pre_Delivery_Inspection_Item__c/fields/Asset_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Asset_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset Milestone</label>
    <referenceTo>AssetMilestone</referenceTo>
    <relationshipLabel>Pre Delivery Inspection Items</relationshipLabel>
    <relationshipName>Pre_Delivery_Inspection_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pre_Delivery_Inspection_Item__c/fields/Check__c.field-meta.xml
<CustomField>
    <fullName>Check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Pre_Delivery_Inspection_Item__c/fields/Pre_Delivery_Inspection__c.field-meta.xml
<CustomField>
    <fullName>Pre_Delivery_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pre Delivery Inspection</label>
    <referenceTo>Pre_Delivery_Inspection__c</referenceTo>
    <relationshipLabel>Pre Delivery Inspection Items</relationshipLabel>
    <relationshipName>Pre_Delivery_Inspection_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Software_Version__c/Software_Version__c.object-meta.xml
<CustomObject>
    <label>Software Version</label>
    <nameField>
        <label>Software Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Software Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Software_Version__c/fields/Latest_Software_Version__c.field-meta.xml
<CustomField>
    <fullName>Latest_Software_Version__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Latest Software Version</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Check_pdi_item_screen_pdf_Test.cls
@isTest
public class Check_pdi_item_screen_pdf_Test {
    @isTest
    static void testPDIItemsPDF() {
        // Create test data
        
        Account acc = new Account();
        acc.Name = 'testing Account';
        insert acc;
        
        Contact con = new Contact();
        con.LastName = 'testing Contact';
        con.AccountId = acc.Id;
        con.Phone = '9123456789';
        con.Email = 'test@test.com';
        con.Primary_Contact__c = true;
        insert con;
        
        Asset asst = new Asset();
        asst.Name = 'test Asset';
        asst.AccountId = acc.Id;
        asst.ContactId = con.Id;
        insert asst;
        
        Software_Version__c sv = new Software_Version__c();
        sv.Name = 'test version';
        sv.Latest_Software_Version__c = true;
        insert sv;
        
        Product2 prod = new Product2();
        prod.Name = 'test product';
        prod.HSN_Code__c = '123';
        prod.Type__c = 'Vehicle';
        insert prod;
        
        VehicleDefinition vd = new VehicleDefinition();
        vd.Name = 'test VehicleDefinition';
        vd.ProductId = prod.Id;
        insert vd;
        
        Vehicle vac = new Vehicle();
        vac.Name = 'test vehicle';
        vac.CurrentOwnerId = acc.Id;
        vac.Charger_PC_Number__c = '123CC';
        vac.VehicleRegistrationNumber = '123';
        vac.VehicleIdentificationNumber = 'NeoCity2022ZXi';
        vac.VehicleDefinitionId = vd.Id;
        vac.Software_Version__c = sv.Id;
        vac.AssetId = asst.Id;
        insert vac;

        Pre_Delivery_Inspection__c pdi = new Pre_Delivery_Inspection__c();
        pdi.Parameter__c = 'Test Parameter';
        pdi.Description__c = 'Test Description';
        pdi.Attribute__c = 'Documentation/ Hardware verification';
        insert pdi;        
         
        AssetMilestone milestone1 = new AssetMilestone();
        milestone1.Name = 'Test Milestone';
        milestone1.AssetId = asst.Id;
        milestone1.UsageType = 'Automotive';
        milestone1.MilestoneDate = System.today();
        milestone1.MilestoneType = 'Order Received';
        milestone1.Stage = 'Active';
        milestone1.VehicleId = vac.Id;
        insert milestone1;
        
        AssetMilestone milestone2 = new AssetMilestone();
        milestone2.Name = 'Test Milestone';
        milestone2.AssetId = asst.Id;
        milestone2.UsageType = 'Automotive';
        milestone2.MilestoneDate = System.today();
        milestone2.MilestoneType = 'Manufactured';
        milestone2.Stage = 'Active';
        milestone2.VehicleId = vac.Id;
        insert milestone2;
        
        AssetMilestone milestone3 = new AssetMilestone();
        milestone3.Name = 'Test Milestone';
        milestone3.AssetId = asst.Id;
        milestone3.UsageType = 'Automotive';
        milestone3.MilestoneDate = System.today();
        milestone3.MilestoneType = 'Delivered';
        milestone3.Stage = 'Active';
        milestone3.VehicleId = vac.Id;
        insert milestone3;
            
        AssetMilestone milestone4 = new AssetMilestone();
        milestone4.Name = 'Test Milestone';
        milestone4.AssetId = asst.Id;
        milestone4.UsageType = 'Automotive';
        milestone4.MilestoneDate = System.today();
        milestone4.MilestoneType = 'PDI';
        milestone4.Stage = 'Active';
        milestone4.VehicleId = vac.Id;
        insert milestone4;

        Pre_Delivery_Inspection_Item__c pdiItem = new Pre_Delivery_Inspection_Item__c();
        pdiItem.Check__c = false;
        pdiItem.Pre_Delivery_Inspection__c = pdi.Id;
        pdiItem.Asset_Milestone__c = milestone4.Id;
        insert pdiItem;
        
        // Call the method being tested
        Test.startTest();
            PageReference pageRef = Page.Check_pdi_item_screen_pdf; // Add your VF page Name here
            pageRef.getParameters().put('id', String.valueOf(vac.Id));
            Test.setCurrentPage(pageRef);
            Check_pdi_item_screen_pdf_controller testAccPlan = new Check_pdi_item_screen_pdf_controller();
        Test.stopTest();
    }
}