force-app/main/default/objects/Daily_Store_Operations__c/Daily_Store_Operations__c.object-meta.xml
<CustomObject>
    <label>Daily Store Operations</label>
    <nameField>
        <displayFormat>DSO-{00000}</displayFormat>
        <label>Daily Store Operations  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Store Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Any__c.field-meta.xml
<CustomField>
    <fullName>Any__c</fullName>
    <label>Any Discrepancies?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Any_Issues_Noted__c.field-meta.xml
<CustomField>
    <fullName>Any_Issues_Noted__c</fullName>
    <label>Any Issues Noted?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Any_Maintenance_Issues__c.field-meta.xml
<CustomField>
    <fullName>Any_Maintenance_Issues__c</fullName>
    <label>Any Maintenance Issues?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Any_Shortages__c.field-meta.xml
<CustomField>
    <fullName>Any_Shortages__c</fullName>
    <label>Any Shortages?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Any_Staff_Issues__c.field-meta.xml
<CustomField>
    <fullName>Any_Staff_Issues__c</fullName>
    <label>Any Staff Issues?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Cash_Deposited__c.field-meta.xml
<CustomField>
    <fullName>Cash_Deposited__c</fullName>
    <label>Cash Deposited</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Cleanliness_Level__c.field-meta.xml
<CustomField>
    <fullName>Cleanliness_Level__c</fullName>
    <label>Cleanliness Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Excellent</fullName>
            </value>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Fair</fullName>
            </value>
            <value>
                <fullName>Poor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Customer_Service_Comments__c.field-meta.xml
<CustomField>
    <fullName>Customer_Service_Comments__c</fullName>
    <label>Customer Service Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Employee_Comments__c.field-meta.xml
<CustomField>
    <fullName>Employee_Comments__c</fullName>
    <label>Employee Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Housekeeping_Comments__c.field-meta.xml
<CustomField>
    <fullName>Housekeeping_Comments__c</fullName>
    <label>Housekeeping Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Inventory_Adjustments__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Adjustments__c</fullName>
    <label>Inventory Adjustments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Inventory_Comments__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Comments__c</fullName>
    <label>Inventory Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Number_of_Customer_Complaints__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Customer_Complaints__c</fullName>
    <label>Number of Customer Complaints</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Number_of_Customer_Returns__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Customer_Returns__c</fullName>
    <label>Number of Customer Returns</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Overall_Customer_Satisfaction__c.field-meta.xml
<CustomField>
    <fullName>Overall_Customer_Satisfaction__c</fullName>
    <label>Overall Customer Satisfaction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Excellent</fullName>
            </value>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Average</fullName>
            </value>
            <value>
                <fullName>Poor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Sales_Cash_Comments__c.field-meta.xml
<CustomField>
    <fullName>Sales_Cash_Comments__c</fullName>
    <label>Sales/Cash Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Staff_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Staff_Attendance__c</fullName>
    <label>Staff Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Stock_Level__c.field-meta.xml
<CustomField>
    <fullName>Stock_Level__c</fullName>
    <label>Stock Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Sufficient</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Store_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Store_Close_Date__c</fullName>
    <label>Store Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Store_Close_Time__c.field-meta.xml
<CustomField>
    <fullName>Store_Close_Time__c</fullName>
    <label>Store Close Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Store_Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Store_Open_Date__c</fullName>
    <label>Store Open Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Store_Open_Time__c.field-meta.xml
<CustomField>
    <fullName>Store_Open_Time__c</fullName>
    <label>Store Open Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Daily_Store_Operations__c/fields/Total_Sales__c.field-meta.xml
<CustomField>
    <fullName>Total_Sales__c</fullName>
    <label>Total Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/dailyStoreOperations.cls
public with sharing class dailyStoreOperations {

    @AuraEnabled(cacheable=false)
    public static void submitDailyStoreOperations(String formData) {
        Map<String, Object> formDataMap = (Map<String, Object>) JSON.deserializeUntyped(formData);
        Daily_Store_Operations__c dso = new Daily_Store_Operations__c();

        System.debug('formDataMap==>'+formDataMap);
        for (String fieldName : formDataMap.keySet()) {
            Object fieldValue = formDataMap.get(fieldName);
            
            if(fieldName == 'openTime'){
                dso.Store_Open_Time__c =  parseISO8601((String) fieldValue);
            } else if(fieldName == 'closeTime' ){
                dso.Store_Close_Time__c = parseISO8601((String) fieldValue);
            } else if(fieldName == 'issuesNoted' ){
                dso.Any_Issues_Noted__c = (String) fieldValue;
            } else if(fieldName == 'comments' ){
                dso.Comments__c = (String) fieldValue;
            } else if(fieldName == 'stockLevel' ){
                dso.Stock_Level__c = (String) fieldValue;
            } else if(fieldName == 'shortage' ){
                dso.Any_Shortages__c = (String) fieldValue;
            } else if(fieldName == 'inventoryAdjustments' ){
                dso.Inventory_Adjustments__c = (String) fieldValue;
            } else if(fieldName == 'inventoryComments' ){
                dso.Inventory_Comments__c = (String) fieldValue;
            } else if(fieldName == 'totalSales' ){
                dso.Total_Sales__c = Decimal.valueOf((String) fieldValue);
            } else if(fieldName == 'cashDeposited' ){
                dso.Cash_Deposited__c = Decimal.valueOf((String) fieldValue);
            } else if(fieldName == 'discrepancies' ){
                dso.Any__c = (String) fieldValue;
            } else if(fieldName == 'salesCashComments' ){
                dso.Sales_Cash_Comments__c = (String) fieldValue;
            } else if(fieldName == 'customerComplaints' ){
                dso.Number_of_Customer_Complaints__c = Decimal.valueOf((String) fieldValue);
            } else if(fieldName == 'customerReturns' ){
                dso.Number_of_Customer_Returns__c = Decimal.valueOf((String) fieldValue);
            } else if(fieldName == 'customerSatisfaction' ){
                dso.Overall_Customer_Satisfaction__c = (String) fieldValue;
            } else if(fieldName == 'customerServiceComments' ){
                dso.Customer_Service_Comments__c = (String) fieldValue;
            } else if(fieldName == 'cleanlinessLevel' ){
                dso.Cleanliness_Level__c = (String) fieldValue;
            } else if(fieldName == 'maintenanceIssues' ){
                dso.Any_Maintenance_Issues__c = (String) fieldValue;
            } else if(fieldName == 'housekeepingComments' ){
                dso.Housekeeping_Comments__c = (String) fieldValue;
            } else if(fieldName == 'staffAttendance' ){
                dso.Staff_Attendance__c = (String) fieldValue;
            } else if(fieldName == 'staffIssues' ){
                dso.Any_Staff_Issues__c = (String) fieldValue;
            } else if(fieldName == 'employeeComments' ){
                dso.Employee_Comments__c = (String) fieldValue;
            }else if(fieldName == 'openDate' ){
                dso.Store_Open_Date__c = Date.valueOf((String) fieldValue);
            }else if(fieldName == 'closeDate' ){
                dso.Store_Close_Date__c = Date.valueOf((String) fieldValue);
            }
        }

        insert dso;
    }

    public static Time parseISO8601(String timeString) {
        List<String> timeComponents = timeString.split(':');
        Integer hours = Integer.valueOf(timeComponents[0]);
        Integer minutes = Integer.valueOf(timeComponents[1]);
        // Assuming seconds are optional, you can add logic to handle them if necessary
    
        return Time.newInstance(hours, minutes, 0, 0);
    }
    
    

    
}