force-app/main/default/objects/Sales_Consumption__c/Sales_Consumption__c.object-meta.xml
<CustomObject>
    <label>Sales Consumption</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Sales Consumption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Consumptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Consumption__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <formula>Order__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dealer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Consumption__c/fields/Manual_Date_Test__c.field-meta.xml
<CustomField>
    <fullName>Manual_Date_Test__c</fullName>
    <label>Manual Date Test</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Consumption__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Sales Consumptions</relationshipLabel>
    <relationshipName>Sales_Consumptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Consumption__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Sales Consumptions</relationshipLabel>
    <relationshipName>Sales_Consumptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Consumption__c/fields/Product_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Product_Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Inventory</label>
    <referenceTo>ProductItem</referenceTo>
    <relationshipLabel>Sales Consumptions</relationshipLabel>
    <relationshipName>Sales_Consumptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Consumption__c/fields/Quantity_Consumed__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Consumed__c</fullName>
    <label>Quantity Consumed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Shiva_Batch.cls
public class Shiva_Batch {
    
    public class mslWrapper{
        public Id DealerId;
        public list<productDetailsWrapper> splits;
        
    }
    
    public class productDetailsWrapper{
        public Id ProductId;
        public date startDate;
        public date endDate;
        public integer Quantity;
        public string monthName;
        public integer sequence;
    }
    
    public static void getData(String type ,integer No){
        List<mslWrapper> allConsumption = new List<mslWrapper>();
        mslWrapper mslobject = new mslWrapper();
        
        for (Sales_Consumption__c sale:[SELECT Id, CreatedDate, Quantity_Consumed__c, Dealer__c, 
                                        Product__c,Product_Inventory__r.Account__c, Order__r.AccountId 
                                        FROM Sales_Consumption__c  WHERE    Manual_Date_Test__c >= :System.today().addMonths(-6) 
                                        AND Order__r.Dealer__r.Type != 'Customer' AND Order__r.Account.Type != 'Customer'])
        {
            mslobject.DealerId=sale.Order__r.AccountId;
            productDetailsWrapper prdtdetails = new productDetailsWrapper();
            prdtdetails.ProductId=sale.Product__c;
            
        }
        
        for (ProductConsumed consumed : [
            SELECT Id, ProductItemId, Quantity_Consumed__c, QuantityConsumed, Product2Id, WorkOrder.Service_Center__c,
            CreatedDate
            FROM ProductConsumed
            WHERE
            Manual_Created_Date__c >= :System.today().addMonths(-6)
            AND WorkOrder.Service_Center__r.Type != 'Customer'
        ])
        {
            
        }
        
        
        
        
    }
}