force-app/main/default/objects/Website_Creds__c/Website_Creds__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Website Creds</label>
</CustomObject>

force-app/main/default/objects/Website_Creds__c/fields/BaseURL__c.field-meta.xml
<CustomField>
    <fullName>BaseURL__c</fullName>
    <label>BaseURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestreverseIntegrationUtility.cls
@isTest
public class TestreverseIntegrationUtility {
     public class MockAccessTokenCallout implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{\"code\":200,\"data\":{\"token\":\"xxxxxxxxxxxx\",\"token_type\":\"Bearer\"}}');
            res.setStatusCode(200);
            return res;
        }
    }
    @isTest
    static void testGenerateAccessToken() {
        
        Website_Creds__c rwd = new Website_Creds__c(
            Name = 'Website Creds',
            BaseURL__c = 'https://dummyurl.com',
            ClientId__c = 'TestClientId',
            ClientSecret__c = 'TestClientSecret'
        );
        insert rwd;

        
        Test.setMock(HttpCalloutMock.class, new MockAccessTokenCallout());

        Test.startTest();
        String accessToken = reverseIntegrationUtility.gererateAccessToken();
        Test.stopTest();
    }
}