force-app/main/default/objects/Website_Creds__c/Website_Creds__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Website Creds</label>
</CustomObject>

force-app/main/default/objects/Website_Creds__c/fields/BaseURL__c.field-meta.xml
<CustomField>
    <fullName>BaseURL__c</fullName>
    <label>BaseURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandlerTest.cls
@Istest
public class AccountTriggerHandlerTest {
    @IsTest
    static void testMethodForAccount(){
        Account testAccount = new Account(Name = 'Test Account 1',Type='Customer',Store_Type__c='DODO',Email__c='test@gmail.com');
        insert testAccount;
        Website_Creds__c rwd = new Website_Creds__c(Name='Website Creds', BaseURL__c='https://dummywebsite.com');
        insert rwd;
        testAccount.Email__c='notest@gmail.com';
        Test.startTest();
        update testAccount;
        Test.stopTest();
    }

}