force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_Up__c/Follow_Up__c.object-meta.xml
<CustomObject>
    <label>Follow Up</label>
    <nameField>
        <label>Follow Up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Follow Ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_Up__c/fields/Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Date__c</fullName>
    <label>Follow Up Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Follow_Up__c/fields/FollowUpType__c.field-meta.xml
<CustomField>
    <fullName>FollowUpType__c</fullName>
    <label>FollowUpType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>booking call</fullName>
                <label>Booking Call</label>
            </value>
            <value>
                <fullName>Schedule TR Call</fullName>
            </value>
            <value>
                <fullName>Reschedule TR Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Follow_Up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Waiting for someone else</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MobileApp_EventFollowUpTest.cls
@isTest
public class MobileApp_EventFollowUpTest {
    @isTest
    public static void testGetFollowUps(){
        User usr = UtilityTestClass.createSalesManagerUser();
        
        Account acc = UtilityTestClass.createTestAccount('Test Account', 'C001', 'Test Store', '560076', 'Customer');

        Opportunity opp = UtilityTestClass.createTestOpportunity( 'Test Opportunity', acc.Id, 'RNR', System.today().addDays(30), 10000 );
        
        String OwnerId = UserInfo.getUserId();
        Follow_Up__c followUp = new Follow_Up__c(); 
        followUp.Name = 'Test Follow Up';
        followUp.Opportunity__c = opp.Id;
        followUp.OwnerId = OwnerId;
        followUp.Feedback__c = 'Test Feedback';
        followUp.Follow_Up_Date__c = Date.today();
        followUp.Next_Follow_Up_Date__c = Date.today().addDays(2);
        followUp.Status__c = 'New';
        followUp.FollowUpType__c = 'booking call';
        insert followUp;

        MobileApp_Wrapper.MobileApp_LeadTotalLeadsWrapper wrapper = new MobileApp_Wrapper.MobileApp_LeadTotalLeadsWrapper();
        wrapper.UserId = UserInfo.getUserId();
        wrapper.FilterDate = 'THIS_MONTH'; 
        wrapper.FilterEndRange = null;

        RestRequest req = new RestRequest();
        req.requestUri = '/services/apexrest/EventFollowUp';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(JSON.serialize(wrapper));
        RestContext.request = req;

        RestResponse res = new RestResponse();
        RestContext.response = res;

        MobileApp_EventFollowUp.getFollowUps();
    }
    @isTest
    public static void testGetFollowUps1(){
        RestRequest req = new RestRequest();
        req.requestUri = '/services/apexrest/EventFollowUp';
        req.httpMethod = 'POST';
        req.requestBody = null;
        RestContext.request = req;

        RestResponse res = new RestResponse();
        RestContext.response = res;

        Test.startTest();
        MobileApp_EventFollowUp.getFollowUps();
        Test.stopTest();
    }
    @isTest
    static void testGetFollowUps2() {
        MobileApp_Wrapper.MobileApp_LeadTotalLeadsWrapper wrapper = new MobileApp_Wrapper.MobileApp_LeadTotalLeadsWrapper();
        wrapper.UserId = '';
        wrapper.FilterDate = 'TODAY';

        RestRequest req = new RestRequest();
        req.requestUri = '/services/apexrest/EventFollowUp';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(JSON.serialize(wrapper));
        RestContext.request = req;

        RestResponse res = new RestResponse();
        RestContext.response = res;
        
        MobileApp_EventFollowUp.getFollowUps();

    }

}