force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_Up__c/Follow_Up__c.object-meta.xml
<CustomObject>
    <label>Follow Up</label>
    <nameField>
        <label>Follow Up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Follow Ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_Up__c/fields/Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Date__c</fullName>
    <label>Follow Up Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Follow_Up__c/fields/Follow_Up_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Remarks__c</fullName>
    <label>Follow-Up Primary Remarks</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RNR</fullName>
            </value>
            <value>
                <fullName>Needs more time to decide</fullName>
            </value>
            <value>
                <fullName>Customer Needs More Information</fullName>
            </value>
            <value>
                <fullName>Customer asked to follow up later</fullName>
            </value>
            <value>
                <fullName>Wants to compare with other brands</fullName>
            </value>
            <value>
                <fullName>Wants finance or insurance details</fullName>
            </value>
            <value>
                <fullName>Asking for additional discounts or offers</fullName>
            </value>
            <value>
                <fullName>Wants price list or brochure</fullName>
            </value>
            <value>
                <fullName>Asking about delivery timelines</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Follow_Up__c/fields/FollowUpType__c.field-meta.xml
<CustomField>
    <fullName>FollowUpType__c</fullName>
    <label>FollowUpType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>booking call</fullName>
                <label>Booking Call</label>
            </value>
            <value>
                <fullName>Schedule TR Call</fullName>
            </value>
            <value>
                <fullName>Reschedule TR Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Follow_Up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Waiting for someone else</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Integration_Type__c.field-meta.xml
<CustomField>
    <fullName>Integration_Type__c</fullName>
    <label>Integration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead Creation</fullName>
            </value>
            <value>
                <fullName>Account Registration</fullName>
            </value>
            <value>
                <fullName>Order Creation</fullName>
            </value>
            <value>
                <fullName>Order Update</fullName>
            </value>
            <value>
                <fullName>Payment Creation</fullName>
            </value>
            <value>
                <fullName>Payment Update</fullName>
            </value>
            <value>
                <fullName>VIN Verification</fullName>
            </value>
            <value>
                <fullName>Service Appointment creation</fullName>
            </value>
            <value>
                <fullName>Case creation</fullName>
            </value>
            <value>
                <fullName>Service Milestone Notification</fullName>
            </value>
            <value>
                <fullName>Ozontel WhatsApp</fullName>
            </value>
            <value>
                <fullName>Lead Creation - BikeDekho</fullName>
            </value>
            <value>
                <fullName>Lead Creation - 91Wheels</fullName>
            </value>
            <value>
                <fullName>Lead Creation - HT Auto</fullName>
            </value>
            <value>
                <fullName>Lead Creation - ThinkResult</fullName>
            </value>
            <value>
                <fullName>Lead Creation - WhatsApp</fullName>
            </value>
            <value>
                <fullName>Lead Creation - CarBike360</fullName>
            </value>
            <value>
                <fullName>Lead Creation - EV India</fullName>
            </value>
            <value>
                <fullName>Lead Creation - OzoneTel</fullName>
            </value>
            <value>
                <fullName>Lead creation - BikeWale</fullName>
            </value>
            <value>
                <fullName>Mobile App</fullName>
            </value>
            <value>
                <fullName>SAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Integration Logs</relationshipLabel>
    <relationshipName>Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MobileAPP_CreateFollowUp.cls
@RestResource(urlMapping='/CreateFollowUp')
global class MobileAPP_CreateFollowUp {
    @HttpPost
    global static void createFollowup() { 

            RestRequest req = RestContext.request;
            system.debug(' req ===============>' + req);
            Blob body = req.requestBody;
        try {

            String requestString = req.requestBody != null ? req.requestBody.toString() : '';
            system.debug(' requestString ===============>' + requestString);
            if (String.isBlank(requestString)) {
                MobileApp_Wrapper.setResponse(400, 'Empty request body', null);
                return;
            }
            
            MobileApp_Wrapper.MobileApp_CreateFollowUp wrp = 
                (MobileApp_Wrapper.MobileApp_CreateFollowUp) JSON.deserialize(
                    requestString, 
                    MobileApp_Wrapper.MobileApp_CreateFollowUp.class
                );
            
            system.debug('Request Body: ' + requestString);
            system.debug('Request Body: ' + body);    
            
            if (wrp.UserId == null || String.isBlank(wrp.UserId) || wrp.UserId == '') {
                MobileApp_Wrapper.setResponse(401, 'Please provide UserId', null);
                return;
            }
            if (wrp.LeadId == null  || String.isBlank(wrp.LeadId) || wrp.LeadId == '') {
                MobileApp_Wrapper.setResponse(401, 'Please provide LeadId', null);
                return;
            }
            if (wrp.FollowUpDate == null || String.isBlank(wrp.FollowUpDate) || wrp.FollowUpDate == '') {
                MobileApp_Wrapper.setResponse(401, 'Please provide FollowUpDate', null);
                return;
            }
            if (wrp.FollowUpTime == null || String.isBlank(wrp.FollowUpTime) || wrp.FollowUpTime == '') {
                MobileApp_Wrapper.setResponse(401, 'Please provide FollowUpTime', null);
                return;
            }
            // if (wrp.FollowUpFeedback == null || String.isBlank(wrp.FollowUpFeedback) || wrp.FollowUpFeedback == '') {
            //     MobileApp_Wrapper.setResponse(401, 'Please provide FollowUpFeedback', null);
            //     return;
            // }
            
            String userId = wrp.UserId;
            String leadId = wrp.LeadId;
            String followUpDate = wrp.FollowUpDate;
            String followUpTime = wrp.FollowUpTime;
            String followUpFeedback = wrp.FollowUpFeedback;
            String followUpType = wrp.followUpType;
            String followUpReason = wrp.followUpReason;
            String followUpSubReason = wrp.followUpSubReason;
            String followUpOther = wrp.followUpOther;
            
            system.debug('UserId ========>' + userId);
            system.debug('LeadId ========> ' + LeadId);
            system.debug('followUpDate ========>' + followUpDate);
            system.debug('followUpTime ========>' + followUpTime);
            system.debug('followUpFeedback ========> ' + followUpFeedback);
            system.debug('followUpType ========> ' + followUpType);
            system.debug('followUpReason ========> ' + followUpReason);
            system.debug('followUpSubReason ========> ' + followUpSubReason);
            system.debug('followUpOther ========> ' + followUpOther);

            
            
            Date datePart = Date.valueOf(followUpDate);
            List<String> timeParts = followUpTime.split(':');
            System.debug('timeParts ========>' + timeParts);
            
            Integer hour = Integer.valueOf(timeParts[0]);
            System.debug('hour ========>' + hour);
            
            Integer minute = Integer.valueOf(timeParts[1]);
            System.debug('minute ========>' + minute);
            
            Time timePart = Time.newInstance(hour, minute, 0, 0);
            System.debug('timePart ========>' + timePart);
            
            Datetime followUpDateTime = Datetime.newInstance(datePart, timePart);
            System.debug('followUpDateTime ========>' + followUpDateTime);

            Follow_Up__c followUp = new Follow_Up__c();
            // if(leadId.startsWith('00Q')) {
            //     List<Lead> leadList = [SELECT Id,Name FROM Lead WHERE Id = :leadId LIMIT 1];
            //     if(leadList.size() == 0) {
            //         MobileApp_Wrapper.setResponse(404, 'Lead not found', null);
            //         return;
            //     }else{
            //         followUp.Name = leadList[0].Name + ' Follow Up';
            //     }
            // }
            if(leadId.startsWith('006')) {
                List<Opportunity> oppList = [SELECT Id,Name FROM Opportunity WHERE Id = :leadId LIMIT 1];
                if(oppList.size() == 0) {
                    MobileApp_Wrapper.setResponse(404, 'Opportunity not found', null);
                    return;
                }else{
                    followUp.Name = oppList[0].Name + ' - Follow Up';
                }
            }
            
            followUp.OwnerId = userId;
            // if(leadId.startsWith('00Q')) {
            //     followUp.Lead__c = leadId;
            // }
            if(leadId.startsWith('006')) {
                followUp.Opportunity__c = leadId;
            }
            followUp.Follow_Up_Date__c = followUpDateTime;
            //followUp.Feedback__c = followUpFeedback;
            //followUp.Status__c = 'New';
            followUp.followUpType__c = followUpType;
            followUp.Status__c = followUpReason != null ? followUpReason : 'New';
            followUp.Follow_Up_Remarks__c = followUpSubReason;
            followUp.Feedback__c = followUpOther;
            insert followUp;
            
            if(followUp.Id == null) {
                MobileApp_Wrapper.setResponse(500, 'Follow Up not created', null);
                return;
            }else{

                Integration_Log__c logObj = new Integration_Log__c(
                    Integration_Type__c = 'Mobile App',
                    Request_Payload__c = JSON.serializePretty(body),
                    Response_Payload__c = 'Follow Created successfully: ' + followUp.Id,
                    Status__c = 'Success'
                );
                insert logObj;

                MobileApp_Wrapper.setResponse(200, 'Follow Up Created', null);
            }
        } catch (Exception e) {

            Integration_Log__c logObj = new Integration_Log__c(
                Integration_Type__c = 'Mobile App',
                Request_Payload__c = JSON.serializePretty(body),
                Response_Payload__c = 'Error: ' + e.getMessage(),
                Error_Message__c = 'Exception: ' + e.getMessage(),
                Status__c = 'Failed'
            );
            insert logObj;

            System.debug('Error: ' + e.getStackTraceString() + ' Message ====>' + e.getMessage() + ' Line Number ====>' + e.getLineNumber());
            MobileApp_Wrapper.setResponse(500, 'Internal server error: ' + e.getMessage(), null);
        }
    }
}