force-app/main/default/objects/VOR__c/VOR__c.object-meta.xml
<CustomObject>
    <label>VOR</label>
    <nameField>
        <displayFormat>VOR -{00000}</displayFormat>
        <label>VOR No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOR__c/fields/Ageing__c.field-meta.xml
<CustomField>
    <fullName>Ageing__c</fullName>
    <formula>ROUND(VALUE(TEXT(ROUND((NOW() - CreatedDate) * 24, 2) / 24)), 2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VOR Days</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VOR__c/fields/Job_Card__c.field-meta.xml
<CustomField>
    <fullName>Job_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Card</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>VOR_Managements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VOR__c/fields/VOR_Reason__c.field-meta.xml
<CustomField>
    <fullName>VOR_Reason__c</fullName>
    <label>VOR Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Diagnosis</fullName>
            </value>
            <value>
                <fullName>Awaiting Parts</fullName>
            </value>
            <value>
                <fullName>Insurance Stage 1</fullName>
            </value>
            <value>
                <fullName>Insurance Stage 2</fullName>
            </value>
            <value>
                <fullName>Awaiting Allotment</fullName>
            </value>
            <value>
                <fullName>Customer Approval</fullName>
            </value>
            <value>
                <fullName>Ready for Delivery</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VorListViewDMSController.cls
public with sharing class VorListViewDMSController {
    
    
    @AuraEnabled(cacheable=true)
    public static  List<VOR__c> GetDealerAssociatedVors(String userId ,String vorReason){
        List<VOR__c> vorList = new List<VOR__c>();
        System.debug('UserId' + UserId);
        User loginUser = [SELECT Id, Name, Dealer_Code__c, Profile.Name, IsPartner FROM User WHERE Id = :userId];
        
        if (loginUser.IsPartner) {
            List<User> relatedUsers = [
                SELECT Id, Name FROM User WHERE Dealer_Code__c = :loginUser.Dealer_Code__c
            ];
            List<WorkOrder> relatedJobs = [
                SELECT Id FROM WorkOrder WHERE OwnerId IN :relatedUsers AND Status != 'Canceled'
            ];
            if(vorReason=='without Reason'){
                vorList = [
                    SELECT Id, Name, VOR_Reason__c, Job_card__r.WorkOrderNumber, Job_card__c ,Ageing__c
                    FROM VOR__c 
                    WHERE VOR_Reason__c =null AND Job_Card__c IN :relatedJobs
                ];
            }else if(vorReason=='with Reason'){
                vorList = [
                    SELECT Id, Name, VOR_Reason__c, Job_card__r.WorkOrderNumber, Job_card__c ,Ageing__c
                    FROM VOR__c 
                    WHERE VOR_Reason__c !=null AND Job_Card__c IN :relatedJobs];
            }else if(vorReason=='All'){
                vorList = [
                    SELECT Id, Name, VOR_Reason__c, Job_card__r.WorkOrderNumber, Job_card__c ,Ageing__c
                    FROM VOR__c 
                    WHERE VOR_Reason__c !=null AND Job_Card__c IN :relatedJobs];
            }else{
                vorList = [
                    SELECT Id, Name, VOR_Reason__c, Job_card__r.WorkOrderNumber, Job_card__c ,Ageing__c
                    FROM VOR__c 
                    WHERE VOR_Reason__c =: vorReason AND Job_Card__c IN :relatedJobs];
            }
        }else{
            system.debug('this is not partner user ---'+userId);
        }
        
        return vorList;
    }
    
}