force-app/main/default/objects/Integration_Log__c/fields/Integration_Type__c.field-meta.xml
<CustomField>
    <fullName>Integration_Type__c</fullName>
    <label>Integration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead Creation</fullName>
            </value>
            <value>
                <fullName>Account Registration</fullName>
            </value>
            <value>
                <fullName>Order Creation</fullName>
            </value>
            <value>
                <fullName>Order Update</fullName>
            </value>
            <value>
                <fullName>Payment Creation</fullName>
            </value>
            <value>
                <fullName>Payment Update</fullName>
            </value>
            <value>
                <fullName>VIN Verification</fullName>
            </value>
            <value>
                <fullName>Service Appointment creation</fullName>
            </value>
            <value>
                <fullName>Case creation</fullName>
            </value>
            <value>
                <fullName>Service Milestone Notification</fullName>
            </value>
            <value>
                <fullName>Ozontel WhatsApp</fullName>
            </value>
            <value>
                <fullName>Lead Creation - BikeDekho</fullName>
            </value>
            <value>
                <fullName>Lead Creation - 91Wheels</fullName>
            </value>
            <value>
                <fullName>Lead Creation - HT Auto</fullName>
            </value>
            <value>
                <fullName>Lead Creation - ThinkResult</fullName>
            </value>
            <value>
                <fullName>Lead Creation - WhatsApp</fullName>
            </value>
            <value>
                <fullName>Lead Creation - CarBike360</fullName>
            </value>
            <value>
                <fullName>Lead Creation - EV India</fullName>
            </value>
            <value>
                <fullName>Lead Creation - OzoneTel</fullName>
            </value>
            <value>
                <fullName>Lead creation - BikeWale</fullName>
            </value>
            <value>
                <fullName>Mobile App</fullName>
            </value>
            <value>
                <fullName>SAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Order</label>
</CustomObject>

force-app/main/default/objects/Order_Payment__c/Order_Payment__c.object-meta.xml
<CustomObject>
    <label>Order Payment</label>
    <nameField>
        <displayFormat>Payment - {0000}</displayFormat>
        <label>Order Payment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>Payments__r.Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Payment__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Payments</relationshipLabel>
    <relationshipName>Order_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Payment__c/fields/Payments__c.field-meta.xml
<CustomField>
    <fullName>Payments__c</fullName>
    <label>Payments</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Order Payments</relationshipLabel>
    <relationshipName>Order_Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Payment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Payment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booking Amount</fullName>
            </value>
            <value>
                <fullName>Down Payment</fullName>
            </value>
            <value>
                <fullName>Full Payment</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Warranty Payment</fullName>
            </value>
            <value>
                <fullName>Accessories Payment</fullName>
            </value>
            <value>
                <fullName>RSA Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payments</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Bank_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Reference_Number__c</fullName>
    <label>Bank Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Card_Name__c.field-meta.xml
<CustomField>
    <fullName>Card_Name__c</fullName>
    <label>Card Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Mode_Of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_Of_Payment__c</fullName>
    <label>Mode Of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AEPS</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Debit Card</fullName>
            </value>
            <value>
                <fullName>Internet Banking</fullName>
            </value>
            <value>
                <fullName>UPI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Awaited</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Source_Of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Source_Of_Payment__c</fullName>
    <label>Source Of Payment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Website</fullName>
                <default>true</default>
                <label>Website</label>
            </value>
            <value>
                <fullName>In Person</fullName>
            </value>
            <value>
                <fullName>PineLabs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <externalId>true</externalId>
    <label>Payment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentAPI.cls
@RestResource(urlMapping='/ManagePayment')
global with sharing class PaymentAPI {
    
    @HttpPost
    global static void createPayment() {
        set<string> paymentTypePicklistValues = new set<string>(); 
        set<string> paymentSourcePicklistValues = new set<string>();
        
        RestResponse res = RestContext.response;
        
        if (res != null) {
            res.addHeader('Content-Type', 'application/json');
        }
        
        RestRequest req = RestContext.request;
        String requestBody = req.requestBody.toString();
        
        // Deserialize the JSON request
        Map<String, Object> requestData = (Map<String, Object>) JSON.deserializeUntyped(requestBody);
        Savepoint sp = Database.setSavepoint();
        try {
            
            Map<String, Object> paymentInfo = (Map<String, Object>) requestData.get('payment_info');
            Map<String, Object> payGwyInfo = (Map<String, Object>) paymentInfo.get('pay_gwy_info'); 
            
            //Check the payment type
            If(PaymentInfo.get('payment_type') == null || PaymentInfo.get('payment_type') == ''){
                throw new CustomException('Required field missing: payment_type');
            }
            
            //Check the order id
            If(requestData.get('order_id') == null || requestData.get('order_id') == ''){
                throw new CustomException('Required field missing: order_id');
            }
            
            //Check the payment source
            If(paymentInfo.get('payment_source') == null || paymentInfo.get('payment_source') == ''){
                throw new CustomException('Required field missing: payment_source');
            }
            
            If(payGwyInfo.get('status') == null || payGwyInfo.get('status') == ''){
                throw new CustomException('Required field missing: status');
            }
            
            String paymentId = (String) paymentInfo.get('payment_id');
            List<Payment__c> Payments = [SELECT Id, Transaction_Id__c FROM Payment__c WHERE Transaction_Id__c = :paymentId LIMIT 1]; 
            
            If(Payments.size()>0)
                throw new CustomException('Duplicate payment found with same Payment Id!');
            
            
            Payment__c newPayment = new Payment__c();
            newPayment.Amount__c = (Decimal) paymentInfo.get('payment_amount');
            newPayment.Bank_Reference_Number__c = PayGwyInfo.get('bank_ref_no') != null?(String) payGwyInfo.get('bank_ref_no'):'';
            newPayment.Card_Name__c = (String) payGwyInfo.get('card_name');
            newPayment.Mode_Of_Payment__c = (String) payGwyInfo.get('payment_mode');
            newPayment.Tracking_Id__c = (String) payGwyInfo.get('tracking_id');
            newPayment.Payment_Status__c = (String) payGwyInfo.get('status');
            newPayment.Description__c = (String) payGwyInfo.get('failure_message');
            newPayment.Transaction_Id__c = paymentId;
            
            List<Schema.PicklistEntry> SourcepicklistValues = Payment__c.Source_Of_Payment__c.getDescribe().getPicklistValues();
            for (Schema.PicklistEntry picklistValue : SourcepicklistValues){
                paymentSourcePicklistValues.add(picklistValue.getValue());
            }
            
            If(!paymentSourcePicklistValues.contains((String)PaymentInfo.get('payment_source'))){
                String availableValues = String.join(paymentSourcePicklistValues, ', ');
                throw new CustomException('Sorry! Unsupported value for payment type (payment_source). Please choose one of the following: ' + availableValues + '.');
            }else{
                newPayment.Source_Of_Payment__c = (String) paymentInfo.get('payment_source');
            }
            
            
            try{
                insert newPayment;
            }catch(exception e){
                throw new CustomException('Error while creating payments: '+e.getMessage());
            }
            
            //Fetch the Order
            String orderId = (String) requestData.get('order_id');
            List<Order> order = [SELECT Id FROM Order WHERE Website_Order_Id__c = :orderId LIMIT 1];
            
            If(order.size() == 0){
                throw new CustomException('Order not found with Order Id (order_id): '+ (String) requestData.get('order_id'));
            }
            
            Order_Payment__c orderPayment = new Order_Payment__c();
            orderPayment.Order__c = order[0].Id;
            orderPayment.Payments__c = newPayment.Id;
            
            List<Schema.PicklistEntry> picklistValues = Order_Payment__c.Type__c.getDescribe().getPicklistValues();
            for (Schema.PicklistEntry picklistValue : picklistValues){
                paymentTypePicklistValues.add(picklistValue.getValue());
            }
            
            If(!paymentTypePicklistValues.contains((String)PaymentInfo.get('payment_type'))){
                String availableValues = String.join(paymentTypePicklistValues, ', ');
                throw new CustomException('Sorry! Unsupported value for payment type (payment_type). Please choose one of the following: ' + availableValues + '.');
            }else{
                orderPayment.Type__c = (String) PaymentInfo.get('payment_type');
            }
            
            try{
                insert orderPayment;
            }catch(exception e){
                throw new CustomException('Error while creating Order payments: '+e.getMessage());
            }
            
            if (res != null) {
                Map<String, Object> response = new Map<String, Object>();
                response.put('status', 'Success');
                response.put('Payment', newPayment.Id);
                response.put('type', 'CREATE');
                res.statusCode = 200;
                res.responseBody = Blob.valueOf(JSON.serialize(response));
            }
            
            // Create a logObj record
            createLogRecord('Payment Creation', requestData, 'Success', (Map<string, object>)JSON.deSerializeUntyped(JSON.serialize(res)));
            
        } catch (Exception e) {
            Database.rollback(sp);
            if (res != null) {
                handleException(res, e, 'Payment Creation', requestData);
            }
        }
    }
    
    @HttpPatch
    global static void updatePayment() {
        
        set<string> paymentTypePicklistValues = new set<string>();
        
        RestResponse res = RestContext.response;
        
        if (res != null) {
            res.addHeader('Content-Type', 'application/json');
        }
        
        RestRequest req = RestContext.request;
        String requestBody = req.requestBody.toString();
        
        // Deserialize the JSON request
        Map<String, Object> requestData = (Map<String, Object>) JSON.deserializeUntyped(requestBody);
        Savepoint sp = Database.setSavepoint();
        
        try {
            
            Map<String, Object> paymentInfo = (Map<String, Object>) requestData.get('payment_info');
            Map<String, Object> payGwyInfo = (Map<String, Object>) paymentInfo.get('pay_gwy_info');
            
            String paymentId = (String) paymentInfo.get('payment_id');
            
            List<Payment__c> existingPayment = [SELECT Id, Amount__c, Bank_Reference_Number__c, Card_Name__c, Mode_Of_Payment__c, Tracking_Id__c, Payment_Status__c, Description__c,Transaction_Id__c FROM Payment__c WHERE Transaction_Id__c =: paymentId LIMIT 1];
            
            If(existingPayment.size()==0)
                throw new CustomException('Sorry! There is no payment record exist with the Payment Id \''+paymentId+'\'');
            
            List<Order_Payment__c> orderPayment = [SELECT Id, Type__c  FROM Order_Payment__c WHERE Payments__c = :existingPayment[0].Id LIMIT 1];
            
            If(orderPayment.size()==0)
                throw new CustomException('Sorry! There is no payment record exist with the Payment Id \''+paymentId+'\'');
            
            //Checking the Order Payment types
            
            String paymentType = (String) paymentInfo.get('payment_type');
            
            List<Schema.PicklistEntry> picklistValues = Order_Payment__c.Type__c.getDescribe().getPicklistValues();
            for (Schema.PicklistEntry picklistValue : picklistValues){
                paymentTypePicklistValues.add(picklistValue.getValue());
            }
            
            If(!paymentTypePicklistValues.contains((String)PaymentInfo.get('payment_type'))){
                String availableValues = String.join(paymentTypePicklistValues, ', ');
                throw new CustomException('Sorry! Unsupported value for payment type (payment_type). Please choose one of the following: ' + availableValues + '.');
            }
            
            If(orderPayment[0].Type__c != paymentType){
                throw new CustomException('Payment Type mismatch!');
            }
            
            //Update the Payments
            existingPayment[0].Amount__c = (Decimal) paymentInfo.get('payment_amount');
            existingPayment[0].Bank_Reference_Number__c = (String) payGwyInfo.get('bank_ref_no');
            existingPayment[0].Card_Name__c = (String) payGwyInfo.get('card_name');
            existingPayment[0].Mode_Of_Payment__c = (String) payGwyInfo.get('payment_mode');
            existingPayment[0].Tracking_Id__c = (String) payGwyInfo.get('tracking_id');
            existingPayment[0].Payment_Status__c = (String) payGwyInfo.get('status');
            existingPayment[0].Description__c = (String) payGwyInfo.get('failure_message');
            
            update existingPayment[0];
            
            Map<String, Object> response = new Map<String, Object>();
            if (res != null) {
                
                response.put('status', 'Success');
                response.put('Payment', existingPayment[0].Id);
                response.put('type', 'UPDATE');
                res.statusCode = 200;
                res.responseBody = Blob.valueOf(JSON.serialize(response));
            }
            
            // Create a logObj record
            createLogRecord('Payment Update', requestData, 'Success', response);
            
        } catch (Exception e) {
            Database.rollback(sp);
            if (res != null) {
                handleException(res, e, 'Payment Update', requestData);
            }
        }
    }
    
    // Helper method to create a log record
    private static void createLogRecord(String integrationType, Map<String, Object> request, String status, Map<string, Object> response) {
        Integration_log__c logObj = new Integration_log__c();
        logObj.Integration_Type__c = integrationType;
        logObj.Request_Payload__c = JSON.serializePretty(request);
        logObj.Response_Payload__c = JSON.serializePretty(response);
        logObj.Status__c = status;
        insert logObj;
    }
    
    // Helper method to handle exceptions and create error log records
    private static void handleException(RestResponse res, Exception e, String integrationType,  Map<String, Object> request) {
        if (res != null) {
            Map<String, Object> response = new Map<String, Object>();
            response.put('status', 'Error');
            response.put('message', e.getMessage());
            res.statusCode = 500;
            res.responseBody = Blob.valueOf(JSON.serialize(response));
            
            createLogRecord(integrationType, request, 'Failed', (Map<string, object>)JSON.deSerializeUntyped(JSON.serialize(res)));
        }
    }
    
    public class CustomException extends Exception {}
}