force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_Up__c/Follow_Up__c.object-meta.xml
<CustomObject>
    <label>Follow Up</label>
    <nameField>
        <label>Follow Up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Follow Ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_Up__c/fields/Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Date__c</fullName>
    <label>Follow Up Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pin_Code__c/Pin_Code__c.object-meta.xml
<CustomObject>
    <label>Pin Code</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pin Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pin_Code__c/fields/Area_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Area_Pincode__c</fullName>
    <externalId>true</externalId>
    <label>Area Pincode</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Pin_Code__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Pin Codes</relationshipLabel>
    <relationshipName>Pin_Codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pin_Code__c/fields/Dealer_Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer/Service Center</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a Dealer/COCO Store/Service Center Account.</errorMessage>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Dealer, COCO Store, Service Center</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pin Codes</relationshipLabel>
    <relationshipName>Pin_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <label>Test Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Drive__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Test_Drive_Status__c.field-meta.xml
<CustomField>
    <fullName>Test_Drive_Status__c</fullName>
    <label>Test Drive Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UtilityTestClass.cls
public class UtilityTestClass {
    public static User createSalesManagerUser() {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Sales Manager' LIMIT 1];
        User u = new User(
            FirstName = 'Anurag', LastName = 'Raichand', Alias = 'smanag', Email = 'sales.manager@example.com', Username = 'sales.manager.' + DateTime.now().getTime() + '@example.com',
            ProfileId = p.Id, TimeZoneSidKey = 'America/New_York', LocaleSidKey = 'en_US', EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US'
        );
        insert u; return u;
    }
    
    public static User createSalesManagerUser1() {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Sales Manager (Partner)' LIMIT 1];
        Account acc = UtilityTestClass.createTestAccount('Partner Store', 'D001', 'Demo Partner Store','560076', 'Dealer');
        
        Contact con = createTestContact('Partner','Manager','partner.manager@example.com','9876543218',acc.Id, 'Sales');
        
        User u = new User(
            FirstName = 'Partner', LastName = 'Manager', Alias = 'pmanag',  Email = 'partner.manager@example.com', Username = 'partner.manager.' + DateTime.now().getTime() + '@example.com',
            ProfileId = p.Id, TimeZoneSidKey = 'America/New_York', LocaleSidKey = 'en_US', EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', ContactId = con.Id
        );
        insert u; return u;
    }
    
    public static Account createTestAccount(String name, String centerCode, String StoreName, String billingPostalCode, String accType) {
        User ownerUser = [SELECT Id, UserRoleId FROM User WHERE UserRoleId != null LIMIT 1];
        Account acc = new Account(Name = name, Center_Code__c = centerCode, Store_Name__c = StoreName , BillingPostalCode = billingPostalCode, Type = accType );
        acc.OwnerId = ownerUser.Id;
        insert acc; return acc;
    }
    
    public static Lead createLead(){
        Lead lead =  new Lead(
            LastName = 'Test No Conversion', Company = 'Test Company', Status = 'New', Phone = '9009244455', PostalCode = '123456', LeadSource = 'Online', 
            Secondary_Sources__c = 'Google'
        );
        insert lead; return lead;
    }
    
    public static Lead createTestLead(String lastName, String company , String status, String phone, String postalCode, String leadSource, String secondardSources){
        Lead lead =  new Lead( LastName = lastName, Company = company, Status = status, Phone = phone, PostalCode = postalCode, LeadSource = leadSource, Secondary_Sources__c = secondardSources );
        insert lead; return lead;
    }
    
    public static Opportunity createTestOpportunity(String name, Id accountId, String stageName, Date closeDate, Decimal amount) {
        Opportunity opp = new Opportunity( Name = name, AccountId = accountId, StageName = stageName, CloseDate = closeDate, Amount = amount);
        insert opp; return opp;
    }
    
    Public static Test_Drive__c createTestDriver(){
        Lead l = createLead();
        Test_Drive__c testDrive = new Test_Drive__c(Name = 'Test Drive', Lead__c = l.Id, Test_Drive_Status__c = 'New', OwnerId = UserInfo.getUserId() );
        insert testDrive; return testDrive;
    }
    
    Public static Test_Drive__c createTest1Driver(String name,Id opportunity, String testDriveStatus){
        Test_Drive__c testDrive = new Test_Drive__c(Name = name, Opportunity__c = opportunity, Test_Drive_Status__c = testDriveStatus);
        testDrive.OwnerId = UserInfo.getUserId(); testDrive.Test_Drive_Date__c = Date.today();
        insert testDrive; return testDrive;
    }
    
    public static Follow_Up__c createFollowUp(String name, Id lead,  Id opportunity){
        Follow_Up__c FollUp = new Follow_Up__c(Name = name, Follow_Up_Date__c = DateTime.now(), Lead__c = lead, Opportunity__c = opportunity);
        insert FollUp; return FollUp;
    }
    
    public static Pin_Code__c createTestPinCode(Id dealerId, String pincode, String cityName) {
        system.debug('dealerId ====>'+ dealerId);
        system.debug('pincode ==>'+ pincode);
        system.debug('cityName ====>'+ cityName);
        List<Pricebook2> pb = [SELECT Id, Name, IsActive, IsStandard FROM Pricebook2 WHERE IsActive = true AND Name = 'Bengaluru PB' LIMIT 1];
        City__c city = new City__c(Name = cityName, Price_Book__c =pb[0].Id );
        insert city;
        system.debug('city ====>'+ city);
        Pin_Code__c pin = new Pin_Code__c(Area_Pincode__c = pincode, Dealer_Service_Center__c = dealerId, City__c = city.Id);
        system.debug('pin ====>'+ pin);
        insert pin; return pin;
    }
    
    public static Task createTestTask(Id leadId, String status, Date activityDate) {
        Task t = new Task(WhoId = leadId, Subject = 'Call', Status = status, ActivityDate = activityDate);
        insert t; return t;
    }
    
    public static Contact createTestContact(String firstName, String lastName, String mail, String phone,Id accountId, String roleType ){       
        List<Schema.Location> locList = [SELECT Id, Name FROM Location LIMIT 1];
        //Schema.Location loc = locList[0];
        Schema.Location loc = new Schema.Location(Name = 'River Store - Indiranagar', LocationType= 'State');
        insert loc;
        Account acc = UtilityTestClass.createTestAccount('Partner Store', 'D001', 'Demo Partner Store','560076', 'Dealer');
        Contact con = new Contact(FirstName = firstName, LastName = lastName, Email = mail, Phone = phone, AccountId = accountId, Role_Type__c = roleType, Location__c =loc.Id);
        con.Designation__c = 'WM';
        insert con; return con;
    }

}