force-app/main/default/objects/FortnightlyForecastInventory__c/FortnightlyForecastInventory__c.object-meta.xml
<CustomObject>
    <label>FortnightlyForecastInventory</label>
    <nameField>
        <displayFormat>FFI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FortnightlyForecastInventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FortnightlyForecastInventory__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>FortnightlyForecastInventory</relationshipLabel>
    <relationshipName>FortnightlyForecastInventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FortnightlyForecastInventory__c/fields/Available_Inventory_Qty__c.field-meta.xml
<CustomField>
    <fullName>Available_Inventory_Qty__c</fullName>
    <label>Available Inventory Qty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FortnightlyForecastInventory__c/fields/Batch_Executed_Date__c.field-meta.xml
<CustomField>
    <fullName>Batch_Executed_Date__c</fullName>
    <label>Batch Executed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FortnightlyForecastInventory__c/fields/PO_Status__c.field-meta.xml
<CustomField>
    <fullName>PO_Status__c</fullName>
    <label>PO Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>GRN Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FortnightlyForecastInventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>FortnightlyForecastInventory</relationshipLabel>
    <relationshipName>FortnightlyForecastInventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FortnightlyForecastInventory__c/fields/Quantity_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Ordered__c</fullName>
    <label>Quantity Ordered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FortnightlyForecastInventory__c/fields/Six_Months_Average_Consumption__c.field-meta.xml
<CustomField>
    <fullName>Six_Months_Average_Consumption__c</fullName>
    <label>Six Months Average Consumption</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RecordAddProductRequestLineItemNew_Test.cls
@isTest
public class RecordAddProductRequestLineItemNew_Test {
	   
    @testSetup
    static void setupData() {

        // Create Account
        Account acc = new Account(
            Name = 'Test Partner Account'
        );
        insert acc;
        
        // Create Contact
        Contact con = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Email = 'contact@example.com',
            AccountId = acc.Id,
            Designation__c = 'WM',
            Phone = '8990785678'
        );
        insert con;
        
        // Create ProductRequest
        ProductRequest pr = new ProductRequest(
            Status = 'Draft',
            AccountId = acc.Id,
            Account__c = acc.Id,
            ShipmentType = 'STK'
        );
        insert pr;
    }
    
    @isTest
    static void testNotifyAndSendApproval() {
        
        ProductRequest pr = [SELECT Id FROM ProductRequest LIMIT 1];
        
        // Build productsnotSelected JSON
        List<Map<String, Object>> prodList = new List<Map<String, Object>>();
        Map<String, Object> prod1 = new Map<String, Object>{
            'ProductName' => 'Test Product A',
            'ProductCode' => 'TPA001',
            'AllocatedQuantity' => 10,
            'MOQ' => 5,
            'AvailableInventory' => 100
        };
        prodList.add(prod1);
        
        String jsonProducts = JSON.serialize(prodList);
        
        Test.startTest();
        String result = RecordAddProductRequestLineItemNew.notifyAndSendApprovalForUnselectedItems(
            jsonProducts,
            pr.Id
        );
        Test.stopTest();
        
        System.assertEquals('Done', result, 'The method should return Done for valid data');
    }
    
    
    // Method to create Test User
    private static User createTestUser(String alias, String profileName) {
        Profile p = [SELECT Id FROM Profile WHERE Name = :profileName LIMIT 1];
        
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        
        Contact con = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            AccountId = acc.Id,
            Phone = '7899037383'
        );
        insert con;
        
        User u = new User(
            Username = alias + DateTime.now().getTime() + '@test.com',
            Alias = alias,
            Email = alias + '@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'User',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            TimeZoneSidKey = 'America/Los_Angeles',
            ProfileId = p.Id
            //ContactId = con.Id
        );
        insert u;
        return u;
    }
    
    @IsTest
    static void testGetAllForecastQuantityUpdated() {
        User u = createTestUser('tusr', 'Standard User');
        
        // Create product
        Product2 prod = new Product2(
            Name = 'Test Product',
            ProductCode = 'TP-001',
            Type__c = 'Parts',
            IsActive = true,
            HSN_Code__c = 'HSN-3874'
        );
        insert prod;
        
        // Create FortnightlyForecastInventory__c record
        FortnightlyForecastInventory__c fRec = new FortnightlyForecastInventory__c(
            Account__c = u.Contact.AccountId,
            Product__c = prod.Id,
            Six_Months_Average_Consumption__c = 10,
            Batch_Executed_Date__c = Date.today(),
            PO_Status__c = '',
            Quantity_Ordered__c = 5,
            Available_Inventory_Qty__c = 2
        );
        insert fRec;
        
        Test.startTest();
        
        List<String> filters = new List<String>{'Service','Sales','Merchandise','Accessories'};
        
        for (String filterVal : filters) {
            List<RecordAddProductRequestLineItemNew.ForecastWrapper> result =
                RecordAddProductRequestLineItemNew.getAllForcastQuantityUpdated(u.Id, filterVal);
            
            System.assertNotEquals(null, result, 'Result should not be null for filter: ' + filterVal);
        }
        Test.stopTest();
    }
}