force-app/main/default/objects/Store_Details__mdt/Store_Details__mdt.object-meta.xml
<CustomObject>
    <label>Store Details</label>
    <pluralLabel>Store Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/Store_Details__mdt/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <label>Dealer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <label>Test Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Drive__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Ride_Type__c.field-meta.xml
<CustomField>
    <fullName>Ride_Type__c</fullName>
    <label>Ride Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HTR</fullName>
            </value>
            <value>
                <fullName>STR</fullName>
            </value>
            <value>
                <fullName>Home Ride</fullName>
            </value>
            <value>
                <fullName>Store Ride</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Test_Drive_Status__c.field-meta.xml
<CustomField>
    <fullName>Test_Drive_Status__c</fullName>
    <label>Test Drive Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Test_Ride_Date__c.field-meta.xml
<CustomField>
    <fullName>Test_Ride_Date__c</fullName>
    <label>Test Ride Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ScheduleQueueableIfNoTestRideTest.cls
@IsTest
public class ScheduleQueueableIfNoTestRideTest {
    @IsTest
    public static void testScheduleQueueableIfNoTestRide(){
        
        Store_Details__mdt s1 = new Store_Details__mdt(Name__c='test 1',Dealer_Code__c='100001',IsActive__c=true);
        Store_Details__mdt s2 = new Store_Details__mdt(Name__c='test 2',Dealer_Code__c='100002',IsActive__c=true);
        
        WhatsappIntegration__c mockIntegration = new WhatsappIntegration__c(
            Name = 'WhatsApp API',
            API_Endpoint__c = 'https://api.whatsapp.com/send',
            API_Key__c = 'mock-api-key',
            test_ride_not_taken2__c = 'https://example.com/image.jpg'
        );
        insert mockIntegration;
        
        List<Lead> leadsToInsert = new List<Lead>();
        Lead l1 = new Lead(LastName='Test Lead',Company='Test Company',Status='New',LeadSource='Google',Phone='0987654321',Dealer_Code__c='100001'); 
        Lead l2 = new Lead(LastName='Test Lead 2',Company='Test Company 2',Status='New',LeadSource='Facebook',Phone='1234567890',Dealer_Code__c='100002');
        insert new List<Lead>{l1, l2};
        
        
        Test_Drive__c testDrive1 = new Test_Drive__c(Lead__c = l1.Id,Test_Ride_Date__c = DateTime.now().addHours(-4).addMinutes(-10),Ride_Type__c = 'Home Ride',Test_Drive_Status__c='Scheduled');
        Test_Drive__c testDrive2 = new Test_Drive__c(Lead__c = l2.Id,Test_Ride_Date__c = DateTime.now(), Ride_Type__c = 'Store Ride',Test_Drive_Status__c='Scheduled');
        
        
        Test.startTest();
        insert testDrive1;
        insert testDrive2;
        
        String cronExpression = '0 0 0 1 1 ?';
        System.schedule('Test', cronExpression, new ScheduleQueueableIfNoTestRide());

        Test.stopTest();
    }

}