force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Order</label>
</CustomObject>

force-app/main/default/objects/Order_Payment__c/Order_Payment__c.object-meta.xml
<CustomObject>
    <label>Order Payment</label>
    <nameField>
        <displayFormat>Payment - {0000}</displayFormat>
        <label>Order Payment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Payment__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Payments</relationshipLabel>
    <relationshipName>Order_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Payment__c/fields/Payments__c.field-meta.xml
<CustomField>
    <fullName>Payments__c</fullName>
    <label>Payments</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Order Payments</relationshipLabel>
    <relationshipName>Order_Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Payment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Payment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booking Amount</fullName>
            </value>
            <value>
                <fullName>Down Payment</fullName>
            </value>
            <value>
                <fullName>Full Payment</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Warranty Payment</fullName>
            </value>
            <value>
                <fullName>Accessories Payment</fullName>
            </value>
            <value>
                <fullName>RSA Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payments</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Mode_Of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_Of_Payment__c</fullName>
    <label>Mode Of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AEPS</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Debit Card</fullName>
            </value>
            <value>
                <fullName>Internet Banking</fullName>
            </value>
            <value>
                <fullName>UPI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Awaited</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Source_Of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Source_Of_Payment__c</fullName>
    <label>Source Of Payment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Website</fullName>
                <default>true</default>
                <label>Website</label>
            </value>
            <value>
                <fullName>In Person</fullName>
            </value>
            <value>
                <fullName>PineLabs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <externalId>true</externalId>
    <label>Payment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Software_Version__c/Software_Version__c.object-meta.xml
<CustomObject>
    <label>Software Version</label>
    <nameField>
        <label>Software Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Software Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Website_Creds__c/Website_Creds__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Website Creds</label>
</CustomObject>

force-app/main/default/objects/Website_Creds__c/fields/BaseURL__c.field-meta.xml
<CustomField>
    <fullName>BaseURL__c</fullName>
    <label>BaseURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestScheduleOrderCreationOnWebsite.cls
@isTest
public class TestScheduleOrderCreationOnWebsite {
    @isTest
    static void testSchedule(){
        Account testAccount = new Account(Name = 'Test Account 1',Type='Customer');
        insert testAccount;
        
        Schema.Location testLocation = new Schema.Location(Name = 'Test Location', LocationType = 'State',State__c = 'Karnataka');
        insert testLocation;
        
        Contact con = new Contact(LastName ='Dinesh 1',Phone = '7834878789',AccountId = testAccount.id,Location__c =testLocation.id );
        insert con;
        
        Product2 testProduct = new Product2(Name = 'Test Product 1', IsActive = true,ProductCode='abcd',HSN_Code__c='abcd',Type__c='Vehicle',StockKeepingUnit='RINDIE-MB-9');
        insert testProduct;
        
        Product2 testProduct2 = new Product2(Name = 'Test Product 1', IsActive = true,ProductCode='abcd',HSN_Code__c='abcd',Type__c='Vehicle',StockKeepingUnit='RINDIE-MB-8');
        insert testProduct2;
        
        Id stdPrBk = Test.getStandardPricebookId();
        
        PricebookEntry testPricebookEntry = new PricebookEntry(
            Product2Id = testProduct.Id,
            Pricebook2Id = stdPrBk,
            UnitPrice = 100.0,
            IsActive = true
        );
        insert testPricebookEntry;
        
        Asset testAsset = new Asset(Name='Test Asset 1',AccountId=testAccount.Id,	Product2Id=testProduct.Id);
        insert testAsset;
        
        VehicleDefinition testVD = new VehicleDefinition(Name='Test VehicleDefinition 1',ProductId=testProduct.Id);
        insert testVD;
        
        Software_Version__c testSV = new Software_Version__c(Name='Test Software Version 1');
        insert testSV;
        
        Vehicle testVehicle = new Vehicle(Name='Test Vehicle 2', Account__c=testAccount.Id, AssetId=testAsset.Id,  VehicleDefinitionId=testVD.Id, VehicleIdentificationNumber='A2B3',  Software_Version__c=testSV.Id, Charger_PC_Number__c='abcd',PDI_Status_Pass__c=true);
        insert testVehicle;
        
        Order oldOrder = new Order( AccountId = testAccount.Id, Status__c = 'Draft',Status='Draft',Assigned_Vehicle__c = testVehicle.Id,EffectiveDate = Date.today(),Pricebook2Id = stdPrBk,Payment_Status__c = 'Completed', Contact__c = con.id,Website_Order_Id__c='98762ze');
        insert oldOrder;
        
        OrderItem testOrderItem = new OrderItem( OrderId = oldOrder.Id, Product2Id = testProduct.Id, UnitPrice = 100.0,Quantity = 1, PricebookEntryId = testPricebookEntry.Id,Offer_Amount__c=45,Offer_Description__c='Test123');
        insert testOrderItem;
        
        Payment__c p = new Payment__c(Mode_Of_Payment__c='Cash',Payment_Status__c='Success',Source_Of_Payment__c='Website',Transaction_Id__c='ev46vt35');
        insert p;
        
        Order_Payment__c opp2 = new Order_Payment__c(Payments__c=p.Id,Type__c='Down Payment',Order__c=oldOrder.Id);
        insert opp2;        
        
        Website_Creds__c rwd = new Website_Creds__c(Name='Website Creds', BaseURL__c='https://dummywebsite.com');
        insert rwd;
        
        List<Id> orderIds = new List<Id>{ oldOrder.Id };
        List<Id> orderItemIds = new List<Id>{ testOrderItem.Id }; 
        List<Id> orderPaymentIds = new List<Id>{opp2.Id};     

        
        ScheduleOrderCreationOnWebsite schedClass = new ScheduleOrderCreationOnWebsite(orderIds);

        ScheduleCreateProductOnWebsite s = new ScheduleCreateProductOnWebsite(orderItemIds);
        
        OrderItemTriggerHandler.OrderItemDeleteDTO dto = new OrderItemTriggerHandler.OrderItemDeleteDTO();
        dto.orderId = oldOrder.Id;
        dto.accountId=testACcount.Id;
        dto.websiteResponseId = 'WebsiteResp123';
        
       ScheduleDeleteOrderItemOnWebsite s1 = new ScheduleDeleteOrderItemOnWebsite(new List<OrderItemTriggerHandler.OrderItemDeleteDTO>{ dto });
        
        
      ScheduleCreatePaymentOnWebsite s2 = new ScheduleCreatePaymentOnWebsite(orderPaymentIds);  
        
        OrderPaymentTriggerHandler.wrapperForDeletePayment  aa = new OrderPaymentTriggerHandler.wrapperForDeletePayment();
        aa.orderId=oldOrder.Id;
        aa.paymentId=p.Id;
        
        ScheduleDeletePaymentOnWebsite s3 = new ScheduleDeletePaymentOnWebsite(new List<OrderPaymentTriggerHandler.wrapperForDeletePayment>{aa});

        Test.startTest();
        schedClass.execute(null);
        s.execute(null);
        s1.execute(null);
        s2.execute(null);
        s3.execute(null);
        Test.stopTest();
    }

}