force-app/main/default/objects/Service_Bay__c/Service_Bay__c.object-meta.xml
<CustomObject>
    <label>Service Bay</label>
    <nameField>
        <displayFormat>BN - {00000}</displayFormat>
        <label>Bay No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Bays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Bay__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Bays</relationshipLabel>
    <relationshipName>Service_Bays</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Bay__c/fields/Technician__c.field-meta.xml
<CustomField>
    <fullName>Technician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technician</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Bays</relationshipLabel>
    <relationshipName>Service_Bays</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Bay__c/fields/Vehicle_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Capacity__c</fullName>
    <label>Vehicle Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AppointmentSlotController_Test.cls
@isTest
public with sharing class AppointmentSlotController_Test {
    
    @isTest
    public static void testAppointmentSlotController() {
        // Create Account
        Account acc = new Account(
            Name = 'Test Account',
            Type = 'Service Center',
            Center_Code__c = '292001',
            Email__c = 'test@gmail.com',
            Phone = '9089786756');
        insert acc;

        // Create Contact
        Contact con = new Contact(
            FirstName = 'Soumya',
            LastName  = 'Mishra',
            AccountId = acc.Id,
            Phone  = '9089786756'
        );
        insert con;

        Service_Bay__c sb = new Service_Bay__c(
            Service_Center__c = acc.Id,
            Vehicle_Capacity__c = 5,
            Technician__c = con.Id
        );
        insert sb;

        Integer count = AppointmentSlotController.getServiceBayCount(acc.Id);
        System.assertEquals(0, count); // Optional assertion


        /*
        AppointmentSlotController.createSlot(
            acc.Id,
            System.today(),
            System.today(),
            '10:00 am',
            '11:00 am',
            2,
            30
        );
        */
    }
}