force-app/main/default/objects/Failure_Code__c/Failure_Code__c.object-meta.xml
<CustomObject>
    <label>Failure Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Failure Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Failure_Code__c/fields/Labour_Code__c.field-meta.xml
<CustomField>
    <fullName>Labour_Code__c</fullName>
    <formula>TFR_Labour_Effect__r.Code_Set__r.Code</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Labour Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Failure_Code__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>TFR Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Activate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Failure_Code__c/fields/TFR_Part_Effect__c.field-meta.xml
<CustomField>
    <fullName>TFR_Part_Effect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TFR Part Effect</label>
    <referenceTo>TFR_Part_Effect__c</referenceTo>
    <relationshipLabel>Failure Code</relationshipLabel>
    <relationshipName>Failure_Code</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Failure_Code__c/fields/VIN_Cut_off__c.field-meta.xml
<CustomField>
    <fullName>VIN_Cut_off__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VIN Cut off</label>
    <referenceTo>TFR__c</referenceTo>
    <relationshipLabel>Failure Code</relationshipLabel>
    <relationshipName>Failure_Code</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Failure_Code__c/fields/VIN_Cut_off_No__c.field-meta.xml
<CustomField>
    <fullName>VIN_Cut_off_No__c</fullName>
    <formula>VIN_Cut_off__r.VIN_Start__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VIN Cut off No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TFR__c/TFR__c.object-meta.xml
<CustomObject>
    <label>VIN Cut off</label>
    <nameField>
        <displayFormat>VINCOFF-{000000}</displayFormat>
        <label>TFR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VIN Cut off</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TFR__c/fields/Sample_Size__c.field-meta.xml
<CustomField>
    <fullName>Sample_Size__c</fullName>
    <label>Sample Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TFR__c/fields/VIN_Start__c.field-meta.xml
<CustomField>
    <fullName>VIN_Start__c</fullName>
    <label>VIN Start</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TFR_Part_Effect__c/TFR_Part_Effect__c.object-meta.xml
<CustomObject>
    <label>TFR Causal Part</label>
    <nameField>
        <displayFormat>TFREP-{000000}</displayFormat>
        <label>TFR Part Effect Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TFR Causal Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TFR_Part_Effect__c/fields/Consequence__c.field-meta.xml
<CustomField>
    <fullName>Consequence__c</fullName>
    <label>Consequence</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TFR_Part_Effect__c/fields/Failure_Code__c.field-meta.xml
<CustomField>
    <fullName>Failure_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Failure Code</label>
    <referenceTo>Failure_Code__c</referenceTo>
    <relationshipName>TFR_Part_Effects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Part_Effect__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>TFR Part Effects</relationshipLabel>
    <relationshipName>TFR_Part_Effects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Part_Effect__c/fields/Root_Cause__c.field-meta.xml
<CustomField>
    <fullName>Root_Cause__c</fullName>
    <label>Root Cause</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TFR_Part_Effect__c/fields/TFR__c.field-meta.xml
<CustomField>
    <fullName>TFR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TFR</label>
    <referenceTo>TFR__c</referenceTo>
    <relationshipLabel>TFR Part Effects</relationshipLabel>
    <relationshipName>TFR_Part_Effects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/TFR_Sample__c.object-meta.xml
<CustomObject>
    <label>TFR Sample</label>
    <nameField>
        <displayFormat>TFRSMP-{00000000}</displayFormat>
        <label>TFR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TFR_Sample</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TFR_Sample__c/fields/Actions_Taken__c.field-meta.xml
<CustomField>
    <fullName>Actions_Taken__c</fullName>
    <label>Actions Taken</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Approved_by__c.field-meta.xml
<CustomField>
    <fullName>Approved_by__c</fullName>
    <formula>Job_Card__r.Owner:User.Manager.FirstName + Job_Card__r.Owner:User.Manager.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approved by</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <formula>Job_Card__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <formula>Job_Card__r.Contact.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Contact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Date_of_Complaint__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Complaint__c</fullName>
    <label>Date of Complaint</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Date_of_Repair__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Repair__c</fullName>
    <formula>Job_Card__r.CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date of Repair</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Date_of_Sale__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Sale__c</fullName>
    <formula>Job_Card__r.Vehicle__r.Purchased_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date of Sale</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Failure_Code__c.field-meta.xml
<CustomField>
    <fullName>Failure_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Failure Code</label>
    <referenceTo>Failure_Code__c</referenceTo>
    <relationshipName>TFR_Sample</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Issue_Severity__c.field-meta.xml
<CustomField>
    <fullName>Issue_Severity__c</fullName>
    <label>Issue Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Job_Card__c.field-meta.xml
<CustomField>
    <fullName>Job_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Card</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>TFR_Sample</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Labour_Code__c.field-meta.xml
<CustomField>
    <fullName>Labour_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Labour Code</label>
    <referenceTo>WorkPlan</referenceTo>
    <relationshipLabel>TFR_Sample</relationshipLabel>
    <relationshipName>TFR_Sample</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Media__c.field-meta.xml
<CustomField>
    <fullName>Media__c</fullName>
    <label>Media</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Observations__c.field-meta.xml
<CustomField>
    <fullName>Observations__c</fullName>
    <label>Observations</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Odometer_Reading__c</fullName>
    <formula>Job_Card__r.Odometer_Reading__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Odometer Reading</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Part__c.field-meta.xml
<CustomField>
    <fullName>Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part</label>
    <referenceTo>WorkOrderLineItem</referenceTo>
    <relationshipName>TFR_Sample</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>TFR_Sample</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/TFR__c.field-meta.xml
<CustomField>
    <fullName>TFR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TFR</label>
    <referenceTo>TFR__c</referenceTo>
    <relationshipName>TFR_Sample</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/VIN_No__c.field-meta.xml
<CustomField>
    <fullName>VIN_No__c</fullName>
    <formula>Job_Card__r.Vehicle_Identification_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VIN No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/VOC__c.field-meta.xml
<CustomField>
    <fullName>VOC__c</fullName>
    <label>VOC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Warranty_Claim_Number__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Claim_Number__c</fullName>
    <formula>Job_Card__r.VDO_Vehicle_Delivery_Order_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warranty Claim Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warranty_Prior__c/Warranty_Prior__c.object-meta.xml
<CustomObject>
    <label>Warranty Prior</label>
    <nameField>
        <displayFormat>WP-{0000}</displayFormat>
        <label>Warranty Prior No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warranty Priors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warranty_Prior__c/fields/FFIR_Number__c.field-meta.xml
<CustomField>
    <fullName>FFIR_Number__c</fullName>
    <label>FFIR Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warranty_Prior__c/fields/Job_Card__c.field-meta.xml
<CustomField>
    <fullName>Job_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Card</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Warranty Priors</relationshipLabel>
    <relationshipName>Warranty_Priors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warranty_Prior__c/fields/Media__c.field-meta.xml
<CustomField>
    <fullName>Media__c</fullName>
    <label>Media</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Warranty_Prior__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Sumbit for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TFRController.cls
public without sharing class TFRController {
    
    @AuraEnabled(Cacheable=true)
    Public Static  List<TFR__c> getExistingVIN(){
         return [SELECT Id,VIN_Start__c,Createddate,Description__c,Is_Active__c FROM  TFR__c where Is_Active__c=true];
    }
    @AuraEnabled
    public static void createTFRWithParts(String vin, String errorCode, String description, List<Object> parts) {
        TFR__c tfr = new TFR__c(
            VIN_Start__c = vin,
            Error_Code__c = errorCode,
            Description__c = description
        );
        insert tfr;
        
        List<TFR_Part_Effect__c> partRecords = new List<TFR_Part_Effect__c>();
        
        for (Object partObj : parts) {
            Map<String, Object> part = (Map<String, Object>)partObj;
            partRecords.add(new TFR_Part_Effect__c(
                TFR__c = tfr.Id,
                Product__c = (String)part.get('partName'),
                //Part_Code__c = (String)part.get('partCode'),
                Consequence__c = (String)part.get('consequence'),
                Root_Cause__c = (String)part.get('rootCause'),
                Comments__c = (String)part.get('comments')
            ));
        }
        
        if (!partRecords.isEmpty()) {
            insert partRecords;
        }
    }
    
    @AuraEnabled
    public static void createMultipleTFRs(List<TFRWrapper> tfrs) {
        system.debug('tfrs---'+tfrs);
        List<TFR__c> tfrToInsert = new List<TFR__c>();
        List<TFR_Part_Effect__c> partsToInsert = new List<TFR_Part_Effect__c>();
        
        for (TFRWrapper tfr : tfrs) {
            TFR__c tfrRec = new TFR__c(
                VIN_Start__c = tfr.vin,
                Error_Code__c = tfr.errorCode,
                Description__c = tfr.description,
                Sample_Size__c=tfr.Required_Sampe_No
            );
            tfrToInsert.add(tfrRec);
        }
        
        insert tfrToInsert;
        
        for (Integer i = 0; i < tfrToInsert.size(); i++) {
            TFR__c insertedTFR = tfrToInsert[i];
            for (ImpactedPartWrapper part : tfrs[i].impactedParts) {
                TFR_Part_Effect__c partRec = new TFR_Part_Effect__c(
                    TFR__c = insertedTFR.Id,
                    //Name__c = part.partName,
                    Product__c = part.partCode,
                    Consequence__c = part.consequence,
                    Root_Cause__c = part.rootCause,
                    Comments__c = part.comments
                );
                partsToInsert.add(partRec);
            }
        }
        
        if (!partsToInsert.isEmpty()) {
            insert partsToInsert;
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static TFRWrapperSample verifyExistingTFR(String partId) {
        WorkOrderLineItem workOrderLineItemRec = null;
        TFR_Sample__c tfrSampleRecord = null;
        
        // Null-safe query for WorkOrderLineItem
        List<WorkOrderLineItem> woliList = [
            SELECT Id, LineItemNumber, PricebookEntryId, Warranty_Prior__c, PricebookEntry.Product2.Name, TFR_Required__c,Warranty_Prior__r.Status__c,
            Failure_Code__c, PricebookEntry.Product2.ProductCode, Quantity, RR_Parts_Category__c, Status, Tax__c,
            Amount_per_Hour__c, CreatedDate, WorkOrder.WorkOrderNumber, PricebookEntry.Product2Id,
            Total_Labour_Charges__c, Total_NDP__c, Grand_Total__c, IGST_Percentage_formula__c,WorkOrder.Status,
            TotalAmount__c, Labour_Code__r.Name, Labour_Code__r.RR_Labour_Charge__c, Replacement_Type__c,
            Labour_Code__r.RR_Efforts_Hours__c, Hours__c, Part_Description__c, Consequential_Part__c, Electrical_Value__c,
            FFIR_Number__c, FFIR_Links__c
            FROM WorkOrderLineItem
            WHERE Id = :partId
            LIMIT 1
        ];
        if (!woliList.isEmpty()) {
            workOrderLineItemRec = woliList[0];
        }
        
        // Null-safe query for TFR_Sample__c
        List<TFR_Sample__c> tfrList = [
            SELECT Actions_Taken__c, Approved_by__c, CreatedById, CreatedDate, Customer_Account__c, Customer_Contact__c,Job_card__r.Status,
            Date_of_Complaint__c, Date_of_Repair__c, Date_of_Sale__c, Failure_Code__c, Id, IsDeleted,
            Issue_Severity__c, Job_Card__c, LastModifiedById, LastModifiedDate, LastReferencedDate,
            LastViewedDate, Media__c, Name, Name__c, Observations__c, Odometer_Reading__c, OwnerId,
            Part__c, Service_Center__c, SystemModstamp, TFR__c, VIN_No__c, VOC__c, Warranty_Claim_Number__c
            FROM TFR_Sample__c
            WHERE Part__c = :partId
            LIMIT 1
        ];
        if (!tfrList.isEmpty()) {
            tfrSampleRecord = tfrList[0];
        }
        
        return new TFRWrapperSample(workOrderLineItemRec, tfrSampleRecord);
    }
    
    
    public static Boolean isVIN2AfterVIN1(String n1, String n2) {
        if (String.isBlank(n1) || String.isBlank(n2) || n1.length() != 17 || n2.length() != 17) {
            return false; // Invalid VINs
        }
        
        try {
            // Extract last 6 digits (production serial number)
            String serial1 = n1.substring(11); // position 12 to 17 (0-based index)
            String serial2 = n2.substring(11);
            
            Integer serialNum1 = Integer.valueOf(serial1);
            Integer serialNum2 = Integer.valueOf(serial2);
            System.debug('serialNum2 > serialNum1'+ (serialNum2 > serialNum1));
            //return serialNum2 > serialNum1;
            return serialNum2 > serialNum1;
        } catch (Exception e) {
            // If serial is not a number or any issue occurs
            System.debug('Error parsing VIN serial numbers: ' + e.getMessage());
            return false;
        }
    }
    
    @AuraEnabled
    Public Static TFRValidationWrapper checkTFRValidation(String VINno,String FailureCodeId){
        // Step 1: Get VIN cutoff from Failure_Code__c
        
        TFRValidationWrapper tfrData = new TFRValidationWrapper(); 
        tfrData.vinNo=VINno;
        tfrData.isTFRApplicable=false;
        tfrData.isPostVinCuttoff=false;
        Boolean isAfterCutoff=false;
        Failure_Code__c fc = [
            SELECT Id, VIN_Cut_off__c, TFR_Part_Effect__c,VIN_Cut_off_No__c 
            FROM Failure_Code__c 
            WHERE Id = :FailureCodeId 
            LIMIT 1
        ];
        
        if(!String.isBlank(fc.VIN_Cut_off__c)){
            System.debug('VIN cutoff found for Failure Code');
            System.debug('VIN cutt off found---'+fc.VIN_Cut_off_No__c);
            System.debug('Job Card Vin---'+VINno);
            isAfterCutoff = isVIN2AfterVIN1(fc.VIN_Cut_off_No__c, VINno);
            if (isAfterCutoff) {
                System.debug('Given VIN is after the cutoff VIN');
                tfrData.isTFRApplicable=true;
                tfrData.isPostVinCuttoff=true;
            } else {
                System.debug('Given VIN is before or equal to the cutoff VIN');
                tfrData.isTFRApplicable=false;
            }
        }else{
            System.debug('No VIN cutoff found for Failure Code');
            tfrData.isTFRApplicable=true;
        }
        
        
        // Step 2 (Optional): You can find existing TFR__c related to this VIN or FailureCode if needed
        List<TFR__c> matchingTFRs = [
            SELECT Id, Name, VIN_Start__c, Error_Code__c 
            FROM TFR__c 
            WHERE VIN_Start__c != null
        ];
        
        for (TFR__c tfr : matchingTFRs) {
            if (!String.isBlank(tfr.VIN_Start__c) && isVIN2AfterVIN1(tfr.VIN_Start__c, VINno)) {
                System.debug('VIN is after TFR VIN start: ' + tfr.Name);
            }
        }
        
        System.debug('tfrData---'+tfrData);
        return tfrData;
        
    }
    
    
    @AuraEnabled
    public static void createMultipleTFRsNew(List<Object> tfrWrappers) {
        system.debug('tfrWrappers---'+tfrWrappers);
        List<TFR__c> tfrRecords = new List<TFR__c>();
        List<Failure_Code__c> fcRecords = new List<Failure_Code__c>();
        List<TFR_Part_Effect__c> partEffectRecords = new List<TFR_Part_Effect__c>();
        
        for (Object wrapper : tfrWrappers) {
            Map<String, Object> tfrMap = (Map<String, Object>)wrapper;
            
            TFR__c tfr = new TFR__c(
                VIN_Start__c = (String)tfrMap.get('vin'),
                Error_Code__c = (String)tfrMap.get('errorCode'),
                Description__c = (String)tfrMap.get('description'),
                Sample_Size__c = Integer.valueOf((String)tfrMap.get('Required_Sampe_No'))
            );
            tfrRecords.add(tfr);
        }
        
        insert tfrRecords;
        
        // Now for each inserted TFR, create related Failure_Code and TFR_Part_Effect
        Integer i = 0;
        for (Object wrapper : tfrWrappers) {
            Map<String, Object> tfrMap = (Map<String, Object>)wrapper;
            TFR__c currentTFR = tfrRecords[i];
            
            // 1. Create Failure_Code__c
            Failure_Code__c fc = new Failure_Code__c(
                Name = 'Auto-Gen FC ' + currentTFR.VIN_Start__c,
                VIN_Cut_off__c = currentTFR.Id
            );
            fcRecords.add(fc);
            i++;
        }
        
        insert fcRecords;
        
        // Now attach TFR_Part_Effect__c
        Integer index = 0;
        for (Object wrapper : tfrWrappers) {
            Map<String, Object> tfrMap = (Map<String, Object>)wrapper;
            List<Object> parts = (List<Object>)tfrMap.get('impactedParts');
            
            TFR__c currentTFR = tfrRecords[index];
            Failure_Code__c relatedFC = fcRecords[index];
            
            for (Object partObj : parts) {
                Map<String, Object> part = (Map<String, Object>)partObj;
                
                TFR_Part_Effect__c pe = new TFR_Part_Effect__c(
                    TFR__c = currentTFR.Id,
                    Failure_Code__c = relatedFC.Id,
                    Product__c = (String)part.get('partName'), // custom field you might need
                    //Product__c = (String)part.get('partCode'),
                    Consequence__c = (String)part.get('consequence'),
                    Root_Cause__c = (String)part.get('rootCause'),
                    Comments__c = (String)part.get('comments')
                );
                partEffectRecords.add(pe);
            }
            
            index++;
        }
        
        insert partEffectRecords;
    }
    
    public static string updatePartsTFRform(list<WorkOrderLineItem> listtoUpdated){
        try{
            update listtoUpdated;
            return 'sucess';
        }Catch (Exception e){
            System.debug('Error update tfr on parts: ' + e.getMessage());
            System.debug('Error at line ' + e.getLineNumber());
            return 'failed';
        }
    }
    
    
    
    // Wrapper Classes
    public class TFRWrapper {
        @AuraEnabled public String vin;
        @AuraEnabled public String errorCode;
        @AuraEnabled public String description;
        @AuraEnabled public Decimal Required_Sampe_No;
        @AuraEnabled public List<ImpactedPartWrapper> impactedParts;
    }
    
    public class ImpactedPartWrapper {
        @AuraEnabled public String partName;
        @AuraEnabled public String partCode;
        @AuraEnabled public String consequence;
        @AuraEnabled public String rootCause;
        @AuraEnabled public String comments;
    }
    
    public class TFRWrapperSample {
        @AuraEnabled public WorkOrderLineItem workOrderLineItemRec { get; set; }
        @AuraEnabled public TFR_Sample__c tfrSampleRecord { get; set; }
        
        public TFRWrapperSample(WorkOrderLineItem woli, TFR_Sample__c tfr) {
            this.workOrderLineItemRec = woli;
            this.tfrSampleRecord = tfr;
        }
    }
    
    public class  TFRValidationWrapper{
        @AuraEnabled 
        public String vinNo;
        @AuraEnabled 
        public Boolean isTFRApplicable;
        @AuraEnabled 
        public Boolean isPostVinCuttoff;
    }
    
}