force-app/main/default/objects/Failure_Code__c/Failure_Code__c.object-meta.xml
<CustomObject>
    <label>Failure Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Failure Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Failure_Code__c/fields/TFR_Labour_Effect__c.field-meta.xml
<CustomField>
    <fullName>TFR_Labour_Effect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TFR Labour Effect</label>
    <referenceTo>TFR_Labour_Effect__c</referenceTo>
    <relationshipLabel>Failure Code</relationshipLabel>
    <relationshipName>Failure_Code</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Failure_Code__c/fields/TFR_Part_Effect__c.field-meta.xml
<CustomField>
    <fullName>TFR_Part_Effect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TFR Part Effect</label>
    <referenceTo>TFR_Part_Effect__c</referenceTo>
    <relationshipLabel>Failure Code</relationshipLabel>
    <relationshipName>Failure_Code</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Failure_Code__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Part</fullName>
            </value>
            <value>
                <fullName>Labour</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TFR__c/TFR__c.object-meta.xml
<CustomObject>
    <label>VIN Cut off</label>
    <nameField>
        <displayFormat>VINCOFF-{000000}</displayFormat>
        <label>TFR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VIN Cut off</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TFR__c/fields/VIN_Start__c.field-meta.xml
<CustomField>
    <fullName>VIN_Start__c</fullName>
    <label>VIN Start</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TFR_Labour_Effect__c/TFR_Labour_Effect__c.object-meta.xml
<CustomObject>
    <label>TFR Labour Effect</label>
    <nameField>
        <displayFormat>TFREL-{000000}</displayFormat>
        <label>TFR Labour Effect Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TFR Labour Effects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TFR_Labour_Effect__c/fields/Code_Set__c.field-meta.xml
<CustomField>
    <fullName>Code_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Code Set</label>
    <referenceTo>CodeSet</referenceTo>
    <relationshipLabel>TFR Labour Effects</relationshipLabel>
    <relationshipName>TFR_Labour_Effects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Labour_Effect__c/fields/Failure_Code__c.field-meta.xml
<CustomField>
    <fullName>Failure_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Failure Code</label>
    <referenceTo>Failure_Code__c</referenceTo>
    <relationshipLabel>TFR Labour Effects</relationshipLabel>
    <relationshipName>TFR_Labour_Effects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Labour_Effect__c/fields/TFR__c.field-meta.xml
<CustomField>
    <fullName>TFR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VIN Cut off</label>
    <referenceTo>TFR__c</referenceTo>
    <relationshipLabel>TFR Labour Effects</relationshipLabel>
    <relationshipName>TFR_Labour_Effects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Part_Effect__c/TFR_Part_Effect__c.object-meta.xml
<CustomObject>
    <label>TFR Causal Part</label>
    <nameField>
        <displayFormat>TFREP-{000000}</displayFormat>
        <label>TFR Part Effect Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TFR Causal Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TFR_Part_Effect__c/fields/Failure_Code__c.field-meta.xml
<CustomField>
    <fullName>Failure_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Failure Code</label>
    <referenceTo>Failure_Code__c</referenceTo>
    <relationshipName>TFR_Part_Effects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Part_Effect__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>TFR Part Effects</relationshipLabel>
    <relationshipName>TFR_Part_Effects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Part_Effect__c/fields/TFR__c.field-meta.xml
<CustomField>
    <fullName>TFR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TFR</label>
    <referenceTo>TFR__c</referenceTo>
    <relationshipLabel>TFR Part Effects</relationshipLabel>
    <relationshipName>TFR_Part_Effects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TriggerOnFailureCodeHelperv2Test.cls
@IsTest
public class TriggerOnFailureCodeHelperv2Test {
    @IsTest
    static void beforeInsertMethods(){
        TFR__c tfr = new TFR__c(VIN_Start__c = 'VIN12345');
        insert tfr;
        
        Product2 prod = new Product2(Name = 'Brake Pad', ProductCode = 'P123', isActive = true, HSN_Code__c='HSN-34U', Type__c='Parts');
        insert prod;
        
        Product2 prod2 = new Product2(Name = 'Brake Pad', ProductCode = 'P123', isActive = true, HSN_Code__c='HSN-34U', Type__c='Parts');
        insert prod2;
        
        Product2 prod3 = new Product2(Name = 'Brake Pad', ProductCode = 'P123', isActive = true, HSN_Code__c='HSN-34U', Type__c='Parts');
        insert prod3;
        
        CodeSet cs = new CodeSet(Name = 'CS-01', Code = 'C01');
        insert cs;
        
        TFR_Part_Effect__c tfrPart = new TFR_Part_Effect__c(TFR__c = tfr.Id,Product__c = prod.Id);
        insert tfrPart;
        
        TFR_Part_Effect__c tfrPart2 = new TFR_Part_Effect__c(TFR__c = tfr.Id,Product__c = prod.Id);
        insert tfrPart2;
        
        TFR_Labour_Effect__c tfrLabour = new TFR_Labour_Effect__c(TFR__c = tfr.Id,Code_Set__c = cs.Id);
        insert tfrLabour;
        
        TFR_Labour_Effect__c tfrLabour2 = new TFR_Labour_Effect__c(TFR__c = tfr.Id,Code_Set__c = cs.Id);
        insert tfrLabour2;
        
        
         Failure_Code__c fc = new Failure_Code__c(
            Name = 'FC-Part',
            TFR_Part_Effect__c = tfrPart.Id,
            TFR_Labour_Effect__c = tfrLabour.Id
        );
        
        Test.startTest();
       
        insert fc;
        
        Failure_Code__c fc2 = new Failure_Code__c(
            Name = 'FC-Part',
            TFR_Labour_Effect__c = tfrLabour.Id
        );
        insert fc2;
        
        fc.TFR_Part_Effect__c = tfrPart2.Id;
        update fc;
        
        fc2.TFR_Part_Effect__c = null;
        update fc2;
        
        fc2.TFR_Labour_Effect__c = tfrLabour2.Id;
        update fc2;
        
        fc2.TFR_Labour_Effect__c = null;
        update fc2;
        
        fc.TFR_Part_Effect__c = null;
        update fc;
        
        
        
        
              
        Test.stopTest();
    }

}