force-app/main/default/objects/Failure_Code__c/Failure_Code__c.object-meta.xml
<CustomObject>
    <label>Failure Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Failure Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Failure_Code__c/fields/VIN_Cut_off__c.field-meta.xml
<CustomField>
    <fullName>VIN_Cut_off__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VIN Cut off</label>
    <referenceTo>TFR__c</referenceTo>
    <relationshipLabel>Failure Code</relationshipLabel>
    <relationshipName>Failure_Code</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR__c/TFR__c.object-meta.xml
<CustomObject>
    <label>VIN Cut off</label>
    <nameField>
        <displayFormat>VINCOFF-{000000}</displayFormat>
        <label>TFR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VIN Cut off</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TFR_Sample__c/TFR_Sample__c.object-meta.xml
<CustomObject>
    <label>TFR Sample</label>
    <nameField>
        <displayFormat>TFRSMP-{00000000}</displayFormat>
        <label>TFR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TFR_Sample</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TFR_Sample__c/fields/Actions_Taken__c.field-meta.xml
<CustomField>
    <fullName>Actions_Taken__c</fullName>
    <label>Actions Taken</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Approved_by__c.field-meta.xml
<CustomField>
    <fullName>Approved_by__c</fullName>
    <formula>Job_Card__r.Owner:User.Manager.FirstName + Job_Card__r.Owner:User.Manager.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approved by</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <formula>Job_Card__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <formula>Job_Card__r.Contact.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Contact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Date_of_Complaint__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Complaint__c</fullName>
    <label>Date of Complaint</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Date_of_Repair__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Repair__c</fullName>
    <formula>Job_Card__r.CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date of Repair</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Date_of_Sale__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Sale__c</fullName>
    <formula>Job_Card__r.Vehicle__r.Purchased_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date of Sale</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Failure_Code__c.field-meta.xml
<CustomField>
    <fullName>Failure_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Failure Code</label>
    <referenceTo>Failure_Code__c</referenceTo>
    <relationshipName>TFR_Sample</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Issue_Severity__c.field-meta.xml
<CustomField>
    <fullName>Issue_Severity__c</fullName>
    <label>Issue Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Job_Card__c.field-meta.xml
<CustomField>
    <fullName>Job_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Card</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>TFR_Sample</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Media__c.field-meta.xml
<CustomField>
    <fullName>Media__c</fullName>
    <label>Media</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Observations__c.field-meta.xml
<CustomField>
    <fullName>Observations__c</fullName>
    <label>Observations</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Odometer_Reading__c</fullName>
    <formula>Job_Card__r.Odometer_Reading__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Odometer Reading</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Part__c.field-meta.xml
<CustomField>
    <fullName>Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part</label>
    <referenceTo>WorkOrderLineItem</referenceTo>
    <relationshipName>TFR_Sample</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>TFR_Sample</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/TFR__c.field-meta.xml
<CustomField>
    <fullName>TFR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TFR</label>
    <referenceTo>TFR__c</referenceTo>
    <relationshipName>TFR_Sample</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/TFR_Post_Vin_Cutt_off__c.field-meta.xml
<CustomField>
    <fullName>TFR_Post_Vin_Cutt_off__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TFR Post Vin Cutt off</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/VIN_No__c.field-meta.xml
<CustomField>
    <fullName>VIN_No__c</fullName>
    <formula>Job_Card__r.Vehicle_Identification_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VIN No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/VOC__c.field-meta.xml
<CustomField>
    <fullName>VOC__c</fullName>
    <label>VOC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TFR_Sample__c/fields/Warranty_Claim_Number__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Claim_Number__c</fullName>
    <formula>Job_Card__r.VDO_Vehicle_Delivery_Order_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warranty Claim Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/JobCardPDFController.cls
public class JobCardPDFController {
    public workorder jobCard { get; set; }
    public List<TFR_Sample__c> tfrSamples { get; set; }
    
    public JobCardPDFController(ApexPages.StandardController std) {
        Id jobCardId ='0WOBh000003WQQfOAO';
        
        jobCard = [
            SELECT Id, workordernumber, Status, Odometer_Reading__c, CreatedDate
            FROM workorder
            WHERE Id = :jobCardId
            LIMIT 1
        ];
        
        tfrSamples = [
            SELECT Actions_Taken__c,Approved_by__c,CreatedById,CreatedDate,
            Customer_Account__c,Customer_Contact__c,Date_of_Complaint__c,
            Date_of_Repair__c,Date_of_Sale__c,Failure_Code__c,Failure_Code__r.name,Id,IsDeleted,
            Issue_Severity__c,Job_Card__c,LastModifiedById,LastModifiedDate,
            LastReferencedDate,LastViewedDate,Media__c,Name,Name__c,Observations__c,
            Odometer_Reading__c,OwnerId,Part__c,Service_Center__c,SystemModstamp,
            TFR_Post_Vin_Cutt_off__c,TFR__c,VIN_No__c,VOC__c,Warranty_Claim_Number__c FROM TFR_Sample__c
            WHERE Job_Card__c = :jobCardId
        ];
    }
}