force-app/main/default/objects/River_Integration_Credential__mdt/River_Integration_Credential__mdt.object-meta.xml
<CustomObject>
    <description>Client Id and secret for Website integration</description>
    <label>River Integration Credential</label>
    <pluralLabel>River Integration Credentials</pluralLabel>
</CustomObject>

force-app/main/default/objects/River_Integration_Credential__mdt/fields/Actual_Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Actual_Endpoint_URL__c</fullName>
    <label>Actual Endpoint URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/River_Integration_Credential__mdt/fields/Authentication_Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Authentication_Endpoint_URL__c</fullName>
    <label>Authentication Endpoint URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/River_Integration_Credential__mdt/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client Id</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/River_Integration_Credential__mdt/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <label>Client Secret</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/UpdateOrderToWebsiteTest.cls
@isTest
private class UpdateOrderToWebsiteTest {

    @isTest
    static void testGenerateJSON() {
        
        // Create test data - Order and related OrderItems
        Map<string,Sobject> dataMap = TestDataFactory.CreateOrder();
        
        OrderItem testOrderItem2 = (OrderItem)dataMap.get('OrderProductId');
        Order testOrder = (order)dataMap.get('OrderId');

        // Start Test
        Test.startTest();

        // Call the generateJSON method
        String jsonString = UpdateOrderToWebsite.generateJSON(testOrder, new List<OrderItem>{testOrderItem2});

        // Stop Test
        Test.stopTest();

        // Verify the generated JSON string
        System.assertNotEquals(null, jsonString, 'JSON string should not be null');
        System.assert(JSON.deserializeUntyped(jsonString) instanceof Map<String, Object>, 'Generated JSON should be a valid Map');
    }

    @isTest
    static void testTokenGenerationAndCallout() {

        // Create test data - Order and related OrderItems
        Map<string,Sobject> dataMap = TestDataFactory.CreateOrder();
        
        OrderItem testOrderItem2 = (OrderItem)dataMap.get('OrderProductId');
        Order testOrder = (order)dataMap.get('OrderId');

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TokenGenerationMock());
        UpdateOrderToWebsite.executeDisplayOutput(testOrder.Id);
        Test.stopTest();
    }
    
    
     @isTest
    static void testActualUpdateCallout() {
        //Get the credentials
        River_Integration_Credential__mdt metadata = [SELECT Id, Client_Id__c, Client_Secret__c, Actual_Endpoint_URL__c, Authentication_Endpoint_URL__c 
                                                      FROM River_Integration_Credential__mdt 
                                                      WHERE DeveloperName = 'Website_Credentials'];
        

        // Create test data - Order and related OrderItems
        Map<string,Sobject> dataMap = TestDataFactory.CreateOrder();
        
        OrderItem testOrderItem2 = (OrderItem)dataMap.get('OrderProductId');
        Order testOrder = (order)dataMap.get('OrderId');
        String jsonString = UpdateOrderToWebsite.generateJSON(testOrder, new List<OrderItem>{testOrderItem2});

        // Start Test
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new ActualUpdateMock());
		string token = 'testtoken';
        UpdateOrderToWebsite.doCallout(token, metadata, jsonString);
        Test.stopTest();

    }
}