force-app/main/default/objects/Warranty_Prior__c/Warranty_Prior__c.object-meta.xml
<CustomObject>
    <label>Warranty Prior</label>
    <nameField>
        <displayFormat>WP-{0000}</displayFormat>
        <label>Warranty Prior No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warranty Priors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warranty_Prior__c/fields/Job_Card__c.field-meta.xml
<CustomField>
    <fullName>Job_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Card</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Warranty Priors</relationshipLabel>
    <relationshipName>Warranty_Priors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warranty_Prior__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Sumbit for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WarrantyPriorApprovalControllerTest.cls
@isTest
public class WarrantyPriorApprovalControllerTest {

    @isTest
    public static void testSubmitApprovalProcess() {
        
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        User testUser = new User(
            Alias = 'abcd',
            Email = 'abcdl@rideriver.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Test',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = profileId.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            Username = 'testabcd@example.com'
        );
        insert testUser;

        Account testAccount = new Account(
            Name = 'Test Account',
            Phone = '9876543210',
            Type = 'Customer'
        );
        insert testAccount;

        WorkOrder testWorkOrder = new WorkOrder(
            AccountId = testAccount.Id
        );
        insert testWorkOrder;

        Warranty_Prior__c warrantyPrior = new Warranty_Prior__c(
            Status__c = 'Pending',
            Job_Card__c = testWorkOrder.Id
        );
        insert warrantyPrior;
        
        Test.startTest();
        
        System.runAs(testUser) {
            String result = WarrantyPriorApprovalController.submitApprovalProcess(
                warrantyPrior.Id, 
                'Parts', 
                'ASM feedback test', 
                'FFIR1234', 
                'Dealer observation', 
                'Test Media', 
                'Standard Value',
                'Standard Value'
            );
            
        }
        Test.stopTest();

    }

    @isTest
    public static void testGetRelatedWarrantyPrior() {
        // Setup test data
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;

        WorkOrder testWorkOrder = new WorkOrder(
            AccountId = testAccount.Id
        );
        insert testWorkOrder;
        // Create a related Warranty Prior record
        Warranty_Prior__c warrantyPrior = new Warranty_Prior__c(
            Status__c = 'Pending',
            Job_Card__c = testWorkOrder.Id
        );
        insert warrantyPrior;

        // Call the getRelatedWarrantyPrior method (logic will be executed or skipped based on context)
        Test.startTest();
        Warranty_Prior__c result = WarrantyPriorApprovalController.getRelatedWarrantyPrior(testAccount.Id);
        Warranty_Prior__c result1 = WarrantyPriorApprovalController.getRelatedWarrantyPrior(null);
        WarrantyPriorApprovalController.checkApprovalStatus(warrantyPrior.ID);
        WarrantyPriorApprovalController.isWarrantySubmittedForApproval(warrantyPrior.ID);
        Test.stopTest();
        

        // Assert that the related warranty prior record is fetched
       // System.assertNotEquals(result, null, 'The related Warranty Prior record should not be null.');
    }
}